# Generated by Django 6.0.3 on 2026-03-06 13:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "free_daily_tokens",
                    models.IntegerField(
                        default=10, help_text="Free AI tokens per user per day"
                    ),
                ),
                (
                    "free_weekly_tokens",
                    models.IntegerField(
                        default=50, help_text="Free AI tokens per user per week"
                    ),
                ),
                (
                    "token_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Price per token in INR",
                        max_digits=6,
                    ),
                ),
                (
                    "feedback_reward",
                    models.IntegerField(
                        default=2, help_text="Tokens awarded for accepted feedback"
                    ),
                ),
                (
                    "min_purchase",
                    models.IntegerField(
                        default=10, help_text="Minimum tokens per purchase"
                    ),
                ),
                (
                    "max_purchase",
                    models.IntegerField(
                        default=500, help_text="Maximum tokens per purchase"
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Configuration",
                "verbose_name_plural": "Token Configuration",
            },
        ),
        migrations.CreateModel(
            name="TokenBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchased_tokens",
                    models.IntegerField(
                        default=0, help_text="Tokens bought by user (never expire)"
                    ),
                ),
                (
                    "daily_tokens_used",
                    models.IntegerField(default=0, help_text="Free tokens used today"),
                ),
                (
                    "weekly_tokens_used",
                    models.IntegerField(
                        default=0, help_text="Free tokens used this week"
                    ),
                ),
                (
                    "total_tokens_used",
                    models.IntegerField(
                        default=0, help_text="Lifetime tokens consumed"
                    ),
                ),
                (
                    "last_daily_reset",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Last date daily counter was reset",
                    ),
                ),
                (
                    "last_weekly_reset",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Last date weekly counter was reset",
                    ),
                ),
                (
                    "feedback_credits",
                    models.IntegerField(
                        default=0, help_text="Tokens earned from accepted feedback"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Balance",
                "verbose_name_plural": "Token Balances",
            },
        ),
        migrations.CreateModel(
            name="TokenTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Token Purchase"),
                            ("feedback_reward", "Feedback Reward"),
                            ("admin_grant", "Admin Grant"),
                            ("refund", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField(help_text="Number of tokens")),
                (
                    "price_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount paid in INR (0 for rewards)",
                        max_digits=8,
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment gateway reference ID",
                        max_length=200,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
