# Generated by Django 5.2.12 on 2026-04-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_adminauditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("token_grant", "Token Grant"),
                    ("token_revoke", "Token Revoke"),
                    ("token_transfer", "Token Transfer"),
                    ("token_view", "Token View"),
                    ("user_view", "User View"),
                    ("user_block", "User Block/Unblock"),
                    ("user_role_update", "User Role Update"),
                    ("user_progress_reset", "User Progress Reset"),
                    ("system_attempt_reset", "System Attempt Reset"),
                    ("system_analytics_clear", "System Analytics Clear"),
                    ("system_rerun_evaluation", "System Rerun Evaluation"),
                ],
                max_length=40,
            ),
        ),
    ]
