# Generated by Django 5.2.12 on 2026-07-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_adminauditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="college",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_bonus_rewarded",
            field=models.BooleanField(default=False),
        ),
    ]
