# Generated by Django 5.2.15 on 2026-07-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_paymentattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="current_session_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="scholarship_test_passed",
            field=models.BooleanField(default=False),
        ),
    ]
