# Generated by Django 5.2.15 on 2026-07-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_current_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenbalance",
            name="purchased_tokens",
            field=models.IntegerField(
                default=50, help_text="Tokens bought by user (never expire)"
            ),
        ),
    ]
