# Generated by Django 5.2.12 on 2026-07-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_tokenbalance_purchased_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="scholarship_granted_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="scholarship_test_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
