# Generated by Django 5.2.12 on 2026-07-18 10:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_customuser_scholarship_granted_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentattempt",
            name="plan",
            field=models.CharField(
                choices=[
                    ("1_month", "1 Month Pass"),
                    ("3_months", "3 Months Pass"),
                    ("1_year", "1 Year Unlimited"),
                    ("scholarship_1_month", "Scholarship 1 Month"),
                    ("legacy", "Legacy Early Bird"),
                ],
                default="legacy",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("1_month", "1 Month Pass"),
                            ("3_months", "3 Months Pass"),
                            ("1_year", "1 Year Unlimited"),
                            ("scholarship_1_month", "Scholarship 1 Month"),
                            ("legacy", "Legacy Early Bird (Lifetime)"),
                            ("admin_grant", "Admin Granted"),
                        ],
                        max_length=30,
                    ),
                ),
                ("plan_display_name", models.CharField(blank=True, max_length=100)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="NULL = lifetime/never expires", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
