# Generated by Django 5.2.12 on 2026-07-19 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_customuser_last_seen"),
        ("questions", "0020_examtrack_announcement_exam_tracks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="active_exam_track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="questions.examtrack",
            ),
        ),
    ]
