# Generated by Django 5.2.12 on 2026-07-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_customuser_active_exam_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="session_key",
            field=models.CharField(
                blank=True,
                help_text="Used to enforce single active session",
                max_length=255,
                null=True,
            ),
        ),
    ]
