# Generated by Django 5.2.12 on 2026-08-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_adminauditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokentransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Token Purchase"),
                    ("feedback_reward", "Feedback Reward"),
                    ("admin_grant", "Admin Grant"),
                    ("admin_revoke", "Admin Revoke"),
                    ("admin_transfer", "Admin Transfer"),
                    ("refund", "Refund"),
                    ("subscription_grant", "Subscription Grant"),
                ],
                max_length=20,
            ),
        ),
    ]
