# Generated by Django 5.2.12 on 2026-08-02 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_tokentransaction_transaction_type"),
        ("questions", "0037_questionimage_strict_explanation_fix"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeShowcaseQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(db_index=True)),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="Display order 0-9 within the year (admin curates 10 per year)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_showcase",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "ordering": ("year", "position"),
                "indexes": [
                    models.Index(fields=["year"], name="accounts_fr_year_f74db7_idx")
                ],
                "unique_together": {("year", "position")},
            },
        ),
    ]
