# Generated by Django 5.2.12 on 2026-08-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_freeshowcasequestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenconfig",
            name="ai_tutor_daily_cap",
            field=models.IntegerField(
                default=2,
                help_text="Free AI Tutor messages/day for free users (premium/admin bypass).",
            ),
        ),
    ]
