import { LegalLayout, buildLegalMetadata } from '@/components/LegalLayout';
import type { Metadata } from 'next';

const title = 'Medical Disclaimer — CrackCMS';
const description = 'CrackCMS is an educational study aid. It does not provide medical advice. AI explanations should be verified against authoritative textbooks before clinical use.';
const canonical = '/disclaimer';

export const metadata: Metadata = buildLegalMetadata({ title, description, canonical });

export default function DisclaimerPage() {
    return (
        <LegalLayout
            title={title}
            description={description}
            lastUpdated="July 21, 2026"
            canonical={canonical}
            schemaType="MedicalWebPage"
        >
            <h2>Educational Purpose Only</h2>
            <p>
                All content on CrackCMS — including question banks, AI tutor responses, mnemonics,
                clinical pearls, and textbook references — is provided <strong>solely for educational
                and exam-preparation purposes</strong>. CrackCMS is not a medical device, is not intended
                to diagnose, treat, cure, or prevent any disease, and is not a substitute for professional
                medical advice, diagnosis, or treatment.
            </p>

            <h2>No Doctor–Patient Relationship</h2>
            <p>
                Use of CrackCMS does not create a doctor–patient, doctor–doctor, or any other professional
                relationship between you and CrackLabs AI or its contributors. Always seek the advice of a
                qualified healthcare provider with any questions you may have regarding a medical
                condition.
            </p>

            <h2>AI-Generated Content</h2>
            <p>
                Explanations, mnemonics, and study notes generated by our AI tutor may contain errors,
                omissions, or outdated information. The AI tutor uses large language models that, despite
                extensive safety measures, can occasionally produce inaccurate or misleading content
                ("hallucinations"). <strong>Always cross-reference AI explanations with authoritative
                textbooks</strong> such as Harrison&apos;s Principles of Internal Medicine, Robbins
                Pathologic Basis of Disease, Bailey &amp; Love&apos;s Short Practice of Surgery, Ghai
                Essential Pediatrics, Park&apos;s Textbook of Preventive Medicine, and Nelson&apos;s
                Textbook of Pediatrics.
            </p>

            <h2>No Clinical Use</h2>
            <p>
                CrackCMS content must not be used as the basis for any clinical decision, patient
                management, or treatment plan. In a clinical setting, defer to your institution&apos;s
                protocols, senior consultants, and approved clinical guidelines.
            </p>

            <h2>Exam Eligibility &amp; Cutoffs</h2>
            <p>
                Information about exam eligibility, syllabus, pattern, cutoffs, and salary is compiled
                from publicly available notifications. Always verify the latest details on the official
                conducting body&apos;s website (upsc.gov.in, nbe.edu.in, aiimsexams.ac.in, nmc.org.in,
                usmle.org, etc.) before applying.
            </p>

            <h2>Emergency</h2>
            <p>
                If you believe you or someone else is experiencing a medical emergency, call your local
                emergency number or go to the nearest hospital immediately. Do not rely on CrackCMS for
                emergency guidance.
            </p>

            <h2>Limitation of Liability</h2>
            <p>
                CrackLabs AI makes no warranties about the completeness, reliability, or accuracy of any
                information on CrackCMS. To the maximum extent permitted by law, CrackLabs AI disclaims
                all liability for any loss or damage arising from reliance on CrackCMS content.
            </p>

            <h2>Report Inaccuracies</h2>
            <p>
                If you spot an error in any question, explanation, or reference, please flag it from the
                question page or email <a href="mailto:editorial@cracklabs.app">editorial@cracklabs.app</a>.
                We review every report and reward accepted corrections with bonus AI tokens.
            </p>
        </LegalLayout>
    );
}
