# Generated by Django 5.2.12 on 2026-07-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgechunk",
            name="license",
            field=models.CharField(
                choices=[
                    ("public_domain", "US Public Domain / Federal Govt"),
                    ("cc_by", "CC BY 4.0"),
                    ("cc_by_sa", "CC BY-SA 4.0"),
                    ("cc_by_nc_sa", "CC BY-NC-SA 4.0"),
                    ("govt_india", "Government of India Open Data"),
                    ("internal", "CrackLabs Internal Content"),
                    ("user_attested", "User-Uploaded with Rights Attestation"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgesource",
            name="license",
            field=models.CharField(
                choices=[
                    ("public_domain", "US Public Domain / Federal Govt"),
                    ("cc_by", "CC BY 4.0"),
                    ("cc_by_sa", "CC BY-SA 4.0"),
                    ("cc_by_nc_sa", "CC BY-NC-SA 4.0"),
                    ("govt_india", "Government of India Open Data"),
                    ("internal", "CrackLabs Internal Content"),
                    ("user_attested", "User-Uploaded with Rights Attestation"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
    ]
