# Generated by Django 5.2.12 on 2026-07-24 12:39

import django.db.models.deletion
import ingestion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0024_rename_ix_dupcluster_method_questions_d_detecti_00b46e_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("total_jobs", models.IntegerField(default=0)),
                ("completed_jobs", models.IntegerField(default=0)),
                ("failed_jobs", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_created_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("sha256_short", models.CharField(db_index=True, max_length=16)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "storage_path",
                    models.CharField(help_text="absolute path on disk", max_length=600),
                ),
                ("file_size", models.BigIntegerField(default=0)),
                ("page_count", models.IntegerField(default=0)),
                (
                    "exam_hint",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("neet_pg", "NEET PG"),
                            ("ini_cet", "INI-CET"),
                            ("fmge", "FMGE"),
                            ("usmle", "USMLE"),
                            ("plab", "PLAB"),
                        ],
                        max_length=20,
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_uploaded_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "parent_exam",
                    models.CharField(
                        choices=[
                            ("neet_pg", "NEET PG"),
                            ("ini_cet", "INI-CET"),
                            ("fmge", "FMGE"),
                            ("usmle", "USMLE"),
                            ("plab", "PLAB"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("crashed", "Crashed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1_render", "Stage 1: Render"),
                            ("2_layout", "Stage 2: Layout"),
                            ("2b_reading_order", "Stage 2b: Reading Order"),
                            ("3_images", "Stage 3: Images"),
                            ("4_tables", "Stage 4: Tables"),
                            ("5_question_blocks", "Stage 5: Question Blocks"),
                            ("6_ocr", "Stage 6: OCR"),
                            ("7_structured", "Stage 7: Structured"),
                            ("7_5_llm", "Stage 7.5: LLM"),
                            ("8_qa", "Stage 8: QA"),
                            ("9_graph", "Stage 9: Graph"),
                            ("10_rag", "Stage 10: RAG"),
                            ("db_writer", "Stage db_writer"),
                            ("conservative_gate", "Conservative Gate"),
                        ],
                        max_length=24,
                    ),
                ),
                ("current_page", models.IntegerField(default=0)),
                ("total_pages", models.IntegerField(default=0)),
                ("progress_pct", models.FloatField(default=0.0)),
                ("qa_v2_production_ready_pct", models.FloatField(default=0.0)),
                ("qa_v2_needs_review_pct", models.FloatField(default=0.0)),
                ("qa_v2_extraction_failure_pct", models.FloatField(default=0.0)),
                ("qa_v2_total_questions", models.IntegerField(default=0)),
                ("questions_imported", models.IntegerField(default=0)),
                ("questions_staged_nr", models.IntegerField(default=0)),
                ("questions_staged_ef", models.IntegerField(default=0)),
                ("images_imported", models.IntegerField(default=0)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("error", models.JSONField(blank=True, default=dict)),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=ingestion.models._default_config
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="ingestion.batchrun",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_created_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retry_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retries",
                        to="ingestion.importjob",
                    ),
                ),
                (
                    "material_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="ingestion.materialasset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_completed_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1_render", "Stage 1: Render"),
                            ("2_layout", "Stage 2: Layout"),
                            ("2b_reading_order", "Stage 2b: Reading Order"),
                            ("3_images", "Stage 3: Images"),
                            ("4_tables", "Stage 4: Tables"),
                            ("5_question_blocks", "Stage 5: Question Blocks"),
                            ("6_ocr", "Stage 6: OCR"),
                            ("7_structured", "Stage 7: Structured"),
                            ("7_5_llm", "Stage 7.5: LLM"),
                            ("8_qa", "Stage 8: QA"),
                            ("9_graph", "Stage 9: Graph"),
                            ("10_rag", "Stage 10: RAG"),
                            ("db_writer", "Stage db_writer"),
                            ("conservative_gate", "Conservative Gate"),
                        ],
                        max_length=24,
                    ),
                ),
                ("last_processed_page", models.IntegerField(default=0)),
                ("current_page", models.IntegerField(default=0)),
                ("token", models.CharField(default="", max_length=64)),
                ("artifact_root", models.CharField(max_length=600)),
                ("artifact_sha16", models.CharField(max_length=16)),
                ("checkpoint_data", models.JSONField(blank=True, default=dict)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="ingestion.importjob",
                    ),
                ),
                (
                    "material_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkpoints",
                        to="ingestion.materialasset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StagedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qa_status",
                    models.CharField(
                        choices=[
                            ("Production Ready", "Production Ready"),
                            ("Needs Review", "Needs Review"),
                            ("Extraction Failure", "Extraction Failure"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("promoted", "Promoted"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("page_number", models.IntegerField(default=0)),
                ("question_number_in_pdf", models.IntegerField(default=0)),
                (
                    "question_payload",
                    models.JSONField(
                        blank=True, default=dict, help_text="full ParsedQuestion dict"
                    ),
                ),
                (
                    "failing_axes",
                    models.JSONField(
                        blank=True, default=list, help_text="list of failing axis names"
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True, help_text="only set for Extraction Failure"
                    ),
                ),
                ("failure_log_paths", models.JSONField(blank=True, default=list)),
                ("review_note", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staged_questions",
                        to="ingestion.importjob",
                    ),
                ),
                (
                    "material_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staged_questions",
                        to="ingestion.materialasset",
                    ),
                ),
                (
                    "published_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staging_records",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "ordering": ["job_id", "page_number", "question_number_in_pdf"],
            },
        ),
        migrations.CreateModel(
            name="ImportArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha16_short", models.CharField(db_index=True, max_length=16)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("render_png", "Render PNG"),
                            ("layout_json", "Layout JSON"),
                            ("image_png", "Image PNG"),
                            ("table_json", "Table JSON"),
                            ("ocr_json", "OCR JSON"),
                            ("qa_per_question_json", "QA Per-Question JSON"),
                            ("qa_summary_json", "QA Summary JSON"),
                            ("db_writer_result", "DB Writer Result"),
                            ("overlay_png", "Overlay PNG"),
                            ("rag_chunk_jsonl", "RAG Chunk JSONL"),
                            ("graph_node_jsonl", "Graph Node JSONL"),
                            ("graph_edge_jsonl", "Graph Edge JSONL"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "path_rel",
                    models.CharField(
                        help_text="path relative to artefact_root", max_length=600
                    ),
                ),
                ("bytes", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="ingestion.importjob",
                    ),
                ),
            ],
            options={
                "ordering": ["job_id", "kind"],
                "indexes": [
                    models.Index(
                        fields=["job", "kind"], name="ingestion_i_job_id_24d783_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ImportJobStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage_name",
                    models.CharField(
                        choices=[
                            ("1_render", "Stage 1: Render"),
                            ("2_layout", "Stage 2: Layout"),
                            ("2b_reading_order", "Stage 2b: Reading Order"),
                            ("3_images", "Stage 3: Images"),
                            ("4_tables", "Stage 4: Tables"),
                            ("5_question_blocks", "Stage 5: Question Blocks"),
                            ("6_ocr", "Stage 6: OCR"),
                            ("7_structured", "Stage 7: Structured"),
                            ("7_5_llm", "Stage 7.5: LLM"),
                            ("8_qa", "Stage 8: QA"),
                            ("9_graph", "Stage 9: Graph"),
                            ("10_rag", "Stage 10: RAG"),
                            ("db_writer", "Stage db_writer"),
                            ("conservative_gate", "Conservative Gate"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("pages_processed", models.IntegerField(default=0)),
                ("pages_skipped", models.IntegerField(default=0)),
                ("artefacts_written", models.IntegerField(default=0)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="ingestion.importjob",
                    ),
                ),
            ],
            options={
                "ordering": ["job_id", "started_at"],
                "indexes": [
                    models.Index(
                        fields=["job", "stage_name"],
                        name="ingestion_i_job_id_34576c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                (
                    "stage_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1_render", "Stage 1: Render"),
                            ("2_layout", "Stage 2: Layout"),
                            ("2b_reading_order", "Stage 2b: Reading Order"),
                            ("3_images", "Stage 3: Images"),
                            ("4_tables", "Stage 4: Tables"),
                            ("5_question_blocks", "Stage 5: Question Blocks"),
                            ("6_ocr", "Stage 6: OCR"),
                            ("7_structured", "Stage 7: Structured"),
                            ("7_5_llm", "Stage 7.5: LLM"),
                            ("8_qa", "Stage 8: QA"),
                            ("9_graph", "Stage 9: Graph"),
                            ("10_rag", "Stage 10: RAG"),
                            ("db_writer", "Stage db_writer"),
                            ("conservative_gate", "Conservative Gate"),
                        ],
                        max_length=24,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="ingestion.importjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["job", "level"], name="ingestion_i_job_id_a6509a_idx"
                    ),
                    models.Index(
                        fields=["job", "created_at"],
                        name="ingestion_i_job_id_3b548e_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="materialasset",
            index=models.Index(
                fields=["sha256_short"], name="ingestion_m_sha256__4cff0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialasset",
            index=models.Index(
                fields=["exam_hint", "uploaded_at"],
                name="ingestion_m_exam_hi_75c8d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["status", "created_at"], name="ingestion_i_status_a3832c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["material_asset", "version"],
                name="ingestion_i_materia_dc11a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["batch_run", "status"], name="ingestion_i_batch_r_9e1aa2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["parent_exam", "status"], name="ingestion_i_parent__7af25a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importcheckpoint",
            index=models.Index(
                fields=["job", "created_at"], name="ingestion_i_job_id_58d484_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stagedquestion",
            index=models.Index(
                fields=["job", "qa_status", "review_status"],
                name="ingestion_s_job_id_8c115b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stagedquestion",
            index=models.Index(
                fields=["material_asset", "qa_status"],
                name="ingestion_s_materia_925a7a_idx",
            ),
        ),
    ]
