release: python manage.py migrate --no-input && python manage.py bootstrap_admin && python manage.py seed_data
web: gunicorn crack_cms.wsgi --bind 0.0.0.0:$PORT --workers 4 --worker-class sync --timeout 120 --log-file -

