release: python manage.py migrate --no-input && python manage.py bootstrap_admin && python manage.py seed_data && python manage.py loaddata questions_fixture.json
web: gunicorn crack_cms.wsgi --log-file -
