# Generated by Django 5.2.12 on 2026-04-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textbooks", "0002_textbookchunk_questionreferenceoverride"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="questionreferenceoverride",
            new_name="textbooks_q_questio_f583ae_idx",
            old_name="textbooks_q_question_bfa14e_idx",
        ),
        migrations.RenameIndex(
            model_name="textbookchunk",
            new_name="textbooks_t_book_na_6c4bc5_idx",
            old_name="textbooks_t_book_na_95d5a9_idx",
        ),
        migrations.RenameIndex(
            model_name="textbookchunk",
            new_name="textbooks_t_is_appr_f19f22_idx",
            old_name="textbooks_t_is_appr_297f49_idx",
        ),
    ]
