# Generated by Django 6.0.3 on 2026-03-04 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("questions", "0003_alter_subject_paper"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailyactivity",
            old_name="questions_correct",
            new_name="correct_answers",
        ),
        migrations.AlterUniqueTogether(
            name="usertopicperformance",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="usertopicperformance",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performances",
                to="questions.topic",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usertopicperformance",
            unique_together={("user", "subject", "topic")},
        ),
    ]
