# Generated by Django 5.2.12 on 2026-04-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_badge_announcement_studystreak_userbadge"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="audience_filter",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="announcement",
            name="deep_link",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="announcement",
            name="delivery_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="announcement",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="failure_report",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
