# Generated by Django 5.2.12 on 2026-07-29 10:04

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0005_announcement_audience_filter_announcement_deep_link_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_id",
                    models.CharField(default=uuid.uuid4, editable=False, max_length=64),
                ),
                ("event_name", models.CharField(db_index=True, max_length=64)),
                ("user_id", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "visitor_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="client-generated UUID for cross-session dedup",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="per-tab / per-session id",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("path", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "page_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "page_group",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("utm_medium", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("utm_term", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "utm_content",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("device_type", models.CharField(blank=True, max_length=32, null=True)),
                ("browser", models.CharField(blank=True, max_length=32, null=True)),
                ("os", models.CharField(blank=True, max_length=32, null=True)),
                ("language", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "country",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("referrer", models.CharField(blank=True, max_length=512, null=True)),
                ("properties", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event_name", "created_at"],
                        name="analytics_a_event_n_e2acee_idx",
                    ),
                    models.Index(
                        fields=["page_type", "created_at"],
                        name="analytics_a_page_ty_8cc4b8_idx",
                    ),
                    models.Index(
                        fields=["page_group", "created_at"],
                        name="analytics_a_page_gr_0835b9_idx",
                    ),
                    models.Index(
                        fields=["utm_campaign", "created_at"],
                        name="analytics_a_utm_cam_8a3603_idx",
                    ),
                    models.Index(
                        fields=["country", "created_at"],
                        name="analytics_a_country_9f69bd_idx",
                    ),
                ],
            },
        ),
    ]
