# Generated by Django 5.2.12 on 2026-07-26 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0026_alter_subject_exam_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_index",
                    models.IntegerField(
                        default=0, help_text="Position within source file"
                    ),
                ),
                ("raw_text", models.TextField(blank=True)),
                ("question_text", models.TextField()),
                ("option_a", models.TextField(blank=True)),
                ("option_b", models.TextField(blank=True)),
                ("option_c", models.TextField(blank=True)),
                ("option_d", models.TextField(blank=True)),
                (
                    "correct_answer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("", "—"),
                        ],
                        max_length=2,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("marks", models.IntegerField(default=1)),
                ("negative_marks", models.FloatField(default=0.0)),
                ("inferred_subject", models.CharField(blank=True, max_length=64)),
                ("inferred_topic", models.CharField(blank=True, max_length=128)),
                ("inferred_difficulty", models.CharField(blank=True, max_length=12)),
                ("inferred_bloom_level", models.CharField(blank=True, max_length=32)),
                ("classification_confidence", models.FloatField(default=0.0)),
                ("classification_meta", models.JSONField(blank=True, default=dict)),
                (
                    "content_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                            ("duplicate", "Duplicate — skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_note", models.TextField(blank=True)),
                ("image_refs", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="material_importer.extractedquestion",
                    ),
                ),
                (
                    "published_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_extracts",
                        to="questions.question",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["material", "position_index"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("partial", "Completed with errors"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("source_label", models.CharField(blank=True, max_length=255)),
                ("root_path", models.CharField(max_length=500)),
                ("total_files", models.IntegerField(default=0)),
                ("files_processed", models.IntegerField(default=0)),
                ("files_failed", models.IntegerField(default=0)),
                ("questions_extracted", models.IntegerField(default=0)),
                ("theory_blocks_extracted", models.IntegerField(default=0)),
                ("images_extracted", models.IntegerField(default=0)),
                ("duplicates_skipped", models.IntegerField(default=0)),
                ("ai_enrichment_queued", models.IntegerField(default=0)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("error_report", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Batch",
                "verbose_name_plural": "Import Batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("stored_path", models.CharField(blank=True, max_length=500)),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("docx", "DOCX"),
                            ("pdf", "PDF"),
                            ("pptx", "PPTX"),
                            ("txt", "Plain text"),
                            ("md", "Markdown"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                (
                    "file_sha256",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "detected_type",
                    models.CharField(
                        choices=[
                            ("mcq_classic", "MCQ (Q1./A./B./C./D./Answer:)"),
                            ("mcq_boxed", "MCQ (Question/Option/correct/incorrect)"),
                            ("mcq_statement", "MCQ (numbered statements + code)"),
                            ("theory", "Theory notes"),
                            ("hybrid", "Theory + MCQs mixed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsed", "Parsed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped (duplicate)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("question_count", models.IntegerField(default=0)),
                ("theory_block_count", models.IntegerField(default=0)),
                ("image_count", models.IntegerField(default=0)),
                ("duplicate_count", models.IntegerField(default=0)),
                ("parse_warnings", models.JSONField(blank=True, default=list)),
                ("parse_errors", models.JSONField(blank=True, default=list)),
                ("parser_used", models.CharField(blank=True, max_length=50)),
                ("duration_ms", models.IntegerField(default=0)),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="material_importer.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ImportedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("stored_path", models.CharField(max_length=500)),
                ("public_url", models.CharField(blank=True, max_length=500)),
                ("mime_type", models.CharField(blank=True, max_length=64)),
                ("width", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                ("size_bytes", models.IntegerField(default=0)),
                ("sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                ("ocr_text", models.TextField(blank=True)),
                (
                    "ocr_status",
                    models.CharField(
                        choices=[
                            ("skipped", "Skipped"),
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="skipped",
                        max_length=16,
                    ),
                ),
                ("is_duplicate", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="material_importer.extractedquestion",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imported_images",
                        to="material_importer.importmaterial",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ImportAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=64)),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="material_importer.importbatch",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="material_importer.importmaterial",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedTheory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_index", models.IntegerField(default=0)),
                ("heading", models.CharField(blank=True, max_length=255)),
                ("subheading", models.CharField(blank=True, max_length=255)),
                ("body_text", models.TextField(blank=True)),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("heading", "Heading"),
                            ("paragraph", "Paragraph"),
                            ("list", "List"),
                            ("table", "Table"),
                            ("callout", "Clinical Pearl / Box"),
                            ("index", "Index / TOC"),
                            ("image_caption", "Image caption"),
                            ("mixed", "Mixed"),
                        ],
                        default="paragraph",
                        max_length=32,
                    ),
                ),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("classification_meta", models.JSONField(blank=True, default=dict)),
                (
                    "content_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_theory",
                        to="material_importer.importmaterial",
                    ),
                ),
            ],
            options={
                "ordering": ["material", "position_index"],
            },
        ),
        migrations.AddField(
            model_name="extractedquestion",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_questions",
                to="material_importer.importmaterial",
            ),
        ),
        migrations.AddIndex(
            model_name="importmaterial",
            index=models.Index(
                fields=["batch", "parse_status"], name="material_im_batch_i_e3ca8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importmaterial",
            index=models.Index(
                fields=["file_sha256"], name="material_im_file_sh_4c3f9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importauditlog",
            index=models.Index(
                fields=["level", "code"], name="material_im_level_3af649_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractedquestion",
            index=models.Index(
                fields=["content_hash"], name="material_im_content_b80450_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractedquestion",
            index=models.Index(fields=["status"], name="material_im_status_908b01_idx"),
        ),
        migrations.AddIndex(
            model_name="extractedquestion",
            index=models.Index(
                fields=["inferred_subject"], name="material_im_inferre_a6f331_idx"
            ),
        ),
    ]
