# Generated by Django 5.2.12 on 2026-07-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_importer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="questions_found",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="questions_rejected",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importmaterial",
            name="questions_found",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importmaterial",
            name="questions_rejected",
            field=models.IntegerField(default=0),
        ),
    ]
