# Generated by Django 5.2.12 on 2026-07-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_importer", "0002_add_counts_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedquestion",
            name="paragraph_index",
            field=models.IntegerField(
                default=-1, help_text="Index of the source paragraph in the DOCX"
            ),
        ),
        migrations.AddField(
            model_name="extractedquestion",
            name="provenance_checksum",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="sha256(question_text + correct_answer + explanation)",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="importedimage",
            name="linked_questions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Per-question image association (P1, Phase 4).",
                related_name="imported_images_m2m",
                to="material_importer.extractedquestion",
            ),
        ),
    ]
