# Generated by Django 5.2.12 on 2026-07-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_importer", "0003_add_provenance_fields"),
        ("questions", "0026_alter_subject_exam_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="extractedquestion",
            constraint=models.UniqueConstraint(
                fields=("material", "content_hash"),
                name="unique_extracted_per_material",
            ),
        ),
    ]
