# Generated by Django 5.2.12 on 2026-07-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="admin_edited",
            field=models.BooleanField(
                default=False, help_text="Flag to protect from automated overwrite"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="eligibility_summary",
            field=models.TextField(
                blank=True, help_text="Short summary of eligibility criteria"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="exam_track_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of exam tracks (e.g. ['cms', 'neet_pg'])",
            ),
        ),
    ]
