# Generated by Django 5.2.12 on 2026-07-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_admin_edited_job_eligibility_summary_and_more"),
        ("questions", "0020_examtrack_announcement_exam_tracks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="exam_tracks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Target exam tracks",
                related_name="jobs",
                to="questions.examtrack",
            ),
        ),
    ]
