# Generated by Django 5.2.12 on 2026-03-03 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "paper",
                    models.IntegerField(
                        choices=[(1, "Paper 1"), (2, "Paper 2")],
                        help_text="CMS Paper number",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name for UI", max_length=50
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Hex color code", max_length=7
                    ),
                ),
            ],
            options={
                "ordering": ["paper", "name"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "importance",
                    models.IntegerField(
                        default=5, help_text="1-10 importance for CMS exam"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtopics",
                        to="questions.topic",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="questions.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "name"],
                "unique_together": {("subject", "name")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("option_a", models.TextField()),
                ("option_b", models.TextField()),
                ("option_c", models.TextField()),
                ("option_d", models.TextField()),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
                ("year", models.IntegerField(db_index=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "concept_tags",
                    models.JSONField(
                        blank=True, default=list, help_text="List of concept tags"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Detailed answer explanation"
                    ),
                ),
                (
                    "concept_explanation",
                    models.TextField(
                        blank=True, help_text="From-basics concept explanation"
                    ),
                ),
                (
                    "mnemonic",
                    models.TextField(
                        blank=True, help_text="Memory trick for this concept"
                    ),
                ),
                ("book_name", models.CharField(blank=True, max_length=200)),
                ("chapter", models.CharField(blank=True, max_length=200)),
                ("page_number", models.CharField(blank=True, max_length=50)),
                (
                    "reference_text",
                    models.TextField(
                        blank=True, help_text="Relevant text from textbook"
                    ),
                ),
                ("exam_source", models.CharField(default="UPSC CMS", max_length=50)),
                (
                    "times_asked",
                    models.IntegerField(
                        default=0, help_text="How many times this concept appeared"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "similar_questions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Questions testing the same concept",
                        to="questions.question",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="questions.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="questions.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "subject"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="questions.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "question")},
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["year", "subject"], name="questions_q_year_508730_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty"], name="questions_q_difficu_5db314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["exam_source"], name="questions_q_exam_so_695cde_idx"
            ),
        ),
    ]
