# Generated by Django 5.2.12 on 2026-03-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="ai_explanation",
            field=models.TextField(
                blank=True, help_text="AI-generated detailed explanation"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="concept_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Keywords for vector similarity matching",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="learning_technique",
            field=models.TextField(
                blank=True, help_text="How to study/approach this concept"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="page_screenshot",
            field=models.ImageField(
                blank=True,
                help_text="Screenshot of textbook page where answer is discussed",
                null=True,
                upload_to="question_screenshots/",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="paper",
            field=models.IntegerField(default=0, help_text="Paper 1 or Paper 2"),
        ),
        migrations.AddField(
            model_name="question",
            name="shortcut_tip",
            field=models.TextField(
                blank=True, help_text="Quick solving trick or shortcut"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Source file (PYQ_2019_Paper1.pdf)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="textbook_references",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {book, chapter, page, excerpt} dicts",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["paper"], name="questions_q_paper_0f1628_idx"),
        ),
    ]
