# Generated by Django 5.2.12 on 2026-03-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questions",
            "0002_question_ai_explanation_question_concept_keywords_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="paper",
            field=models.IntegerField(
                choices=[(1, "Paper 1"), (2, "Paper 2")],
                default=1,
                help_text="CMS Paper number",
            ),
        ),
    ]
