# Generated by Django 5.2.12 on 2026-04-17 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0011_adminaipromptversion_questionaioperationlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionRevisionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="questionfeedback",
            name="notified_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="questionfeedback",
            name="resolution_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="questionfeedback",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionfeedback",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_question_feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="questionfeedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                ],
                db_index=True,
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["is_active", "is_verified_by_admin"],
                name="questions_q_is_acti_3ff97e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["subject", "topic", "year", "difficulty"],
                name="questions_q_subject_907eb9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionfeedback",
            index=models.Index(
                fields=["status", "is_resolved", "created_at"],
                name="questions_q_status_bb36f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionfeedback",
            index=models.Index(
                fields=["question", "status"], name="questions_q_questio_b39bf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionfeedback",
            index=models.Index(
                fields=["category", "status"], name="questions_q_categor_1beaf5_idx"
            ),
        ),
        migrations.AddField(
            model_name="questionrevisionsnapshot",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="question_revision_snapshots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="questionrevisionsnapshot",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revision_snapshots",
                to="questions.question",
            ),
        ),
        migrations.AddIndex(
            model_name="questionrevisionsnapshot",
            index=models.Index(
                fields=["question", "created_at"], name="questions_q_questio_a6f509_idx"
            ),
        ),
    ]
