# Generated by Django 5.2.12 on 2026-07-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0013_question_concept_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="admin_answer_override",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="admin_explanation_override",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="admin_mnemonic_override",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="ai_answer",
            field=models.TextField(blank=True, help_text="AI-generated answer rationale"),
        ),
        migrations.AlterField(
            model_name="question",
            name="ai_mnemonic",
            field=models.TextField(blank=True, help_text="AI-generated mnemonic"),
        ),
    ]
