# Generated by Django 5.2.15 on 2026-07-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0015_questionattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="ai_clinical_pearl",
            field=models.TextField(blank=True, help_text="AI-generated clinical pearl"),
        ),
        migrations.AddField(
            model_name="question",
            name="ai_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="ai_model",
            field=models.CharField(
                blank=True, help_text="Model used for generation", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="ai_version",
            field=models.CharField(
                blank=True, help_text="Prompt/system version", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="video_duration",
            field=models.IntegerField(
                blank=True, help_text="Duration in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="video_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="video_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="video_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="video_thumbnail",
            field=models.URLField(
                blank=True, help_text="Thumbnail URL", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="Supabase storage URL for MP4", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="video_version",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
