# Generated by Django 5.2.12 on 2026-07-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questions",
            "0016_question_ai_clinical_pearl_question_ai_generated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("cms", "UPSC CMS"),
                    ("neet_pg", "NEET PG"),
                    ("usmle", "USMLE"),
                    ("fmge", "FMGE"),
                ],
                default="cms",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("cms", "UPSC CMS"),
                    ("neet_pg", "NEET PG"),
                    ("usmle", "USMLE"),
                    ("fmge", "FMGE"),
                ],
                default="cms",
                help_text="Target exam for this subject",
                max_length=20,
            ),
        ),
    ]
