# Generated by Django 5.2.12 on 2026-07-18 14:59

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0017_question_exam_type_subject_exam_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="admin_edited",
            field=models.BooleanField(
                default=False, help_text="Flag to protect from seed script overwrites"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="display_number",
            field=models.IntegerField(
                blank=True,
                help_text="Number shown to students (scoped by year/paper)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="is_dropped",
            field=models.BooleanField(
                default=False,
                help_text="Dropped/disputed question excluded from scoring",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="needs_review",
            field=models.BooleanField(
                default=False, help_text="Flag for partially digitized or disputed PYQs"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "body",
                    models.TextField(help_text="Rich text content of the announcement"),
                ),
                (
                    "target_exam_track",
                    models.CharField(
                        choices=[
                            ("all", "All Students"),
                            ("cms", "UPSC CMS Only"),
                            ("neet_pg", "NEET PG Only"),
                            ("usmle", "USMLE Only"),
                            ("fmge", "FMGE Only"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific users to see this (overrides exam track)",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
