# Generated by Django 5.2.12 on 2026-07-18 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0018_question_admin_edited_question_display_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
    ]
