# Generated by Django 5.2.12 on 2026-07-19 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0019_alter_question_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. UPSC CMS", max_length=100, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. cms, neet_pg", max_length=20, unique=True
                    ),
                ),
                ("conducting_body", models.CharField(blank=True, max_length=100)),
                ("notification_date", models.DateField(blank=True, null=True)),
                ("application_start", models.DateField(blank=True, null=True)),
                ("application_end", models.DateField(blank=True, null=True)),
                ("exam_date", models.DateField(blank=True, null=True)),
                ("admit_card_date", models.DateField(blank=True, null=True)),
                ("result_date", models.DateField(blank=True, null=True)),
                ("vacancies", models.CharField(blank=True, max_length=100)),
                ("exam_pattern_summary", models.TextField(blank=True)),
                ("eligibility_summary", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="announcement",
            name="exam_tracks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Target exam tracks",
                related_name="announcements",
                to="questions.examtrack",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="exam_track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="questions.examtrack",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="exam_track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="questions.examtrack",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="exam_track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="topics",
                to="questions.examtrack",
            ),
        ),
    ]
