# Generated by Django 5.2.12 on 2026-07-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0020_examtrack_announcement_exam_tracks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_controversial",
            field=models.BooleanField(
                default=False,
                help_text="Flag for questions with ambiguous/controversial answers",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="is_scholarship_eligible",
            field=models.BooleanField(
                default=False,
                help_text="Eligible for scholarship test (balanced, verified)",
            ),
        ),
    ]
