# Generated by Django 5.2.12 on 2026-07-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0021_question_is_controversial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_disputed",
            field=models.BooleanField(
                default=False,
                help_text="Answer key disputed by students or flagged for review",
            ),
        ),
    ]
