# Generated by Django 5.2.12 on 2026-07-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0023_recall_neetpg_fields_and_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="duplicatecluster",
            new_name="questions_d_detecti_00b46e_idx",
            old_name="ix_dupcluster_method",
        ),
        migrations.RenameIndex(
            model_name="duplicatemember",
            new_name="questions_d_questio_a2d1a8_idx",
            old_name="ix_dupmember_question",
        ),
        migrations.RenameIndex(
            model_name="question",
            new_name="questions_q_questio_14b61e_idx",
            old_name="ix_question_type",
        ),
        migrations.RenameIndex(
            model_name="question",
            new_name="questions_q_clinica_542ad8_idx",
            old_name="ix_question_clinical",
        ),
        migrations.RenameIndex(
            model_name="questionimage",
            new_name="questions_q_questio_5861d4_idx",
            old_name="ix_qimage_question",
        ),
        migrations.RenameIndex(
            model_name="questionimage",
            new_name="questions_q_modalit_9c5097_idx",
            old_name="ix_qimage_modality",
        ),
        migrations.RenameIndex(
            model_name="questionimage",
            new_name="questions_q_phash_1632f7_idx",
            old_name="ix_qimage_phash",
        ),
        migrations.RenameIndex(
            model_name="questionimage",
            new_name="questions_q_is_acti_fe1d30_idx",
            old_name="ix_qimage_active",
        ),
        migrations.RenameIndex(
            model_name="questionsource",
            new_name="questions_q_questio_be4f66_idx",
            old_name="ix_qsource_question",
        ),
        migrations.RenameIndex(
            model_name="questionsource",
            new_name="questions_q_recall__48e07f_idx",
            old_name="ix_qsource_page",
        ),
        migrations.RenameIndex(
            model_name="questionsource",
            new_name="questions_q_import__7b281d_idx",
            old_name="ix_qsource_jobid",
        ),
        migrations.RenameIndex(
            model_name="recallsource",
            new_name="questions_r_scan_ty_8be0ad_idx",
            old_name="ix_recall_source_scan",
        ),
        migrations.RenameIndex(
            model_name="recallsource",
            new_name="questions_r_recall__3d0e86_idx",
            old_name="ix_recall_source_recall",
        ),
        migrations.RenameIndex(
            model_name="recallsource",
            new_name="questions_r_is_acti_7f60a5_idx",
            old_name="ix_recall_source_active",
        ),
        migrations.AlterField(
            model_name="question",
            name="clinical_category",
            field=models.CharField(
                choices=[
                    ("clinical", "Clinical"),
                    ("preclinical", "Preclinical"),
                    ("paraclinical", "Paraclinical"),
                ],
                db_index=True,
                default="clinical",
                help_text="Preclinical / Paraclinical / Clinical classification.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("cms", "UPSC CMS"),
                    ("neet_pg", "NEET PG"),
                    ("ini_cet", "INI-CET"),
                    ("usmle", "USMLE"),
                    ("fmge", "FMGE"),
                ],
                default="cms",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single_best", "Single Best Answer"),
                    ("multiple_correct", "Multiple Correct"),
                    ("assertion_reason", "Assertion-Reason"),
                    ("match", "Match the Following"),
                    ("image_based", "Image-Based"),
                    ("numerical", "Numerical"),
                ],
                db_index=True,
                default="single_best",
                help_text="Question format (single best, multiple correct, A/R, image-based, etc.)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="recall_status",
            field=models.CharField(
                choices=[
                    ("recall", "Recall"),
                    ("coaching_compiled", "Coaching Compiled"),
                    ("official_compiled", "Official / Compiled"),
                ],
                db_index=True,
                default="official_compiled",
                help_text="Recall / coaching-compiled / official-compiled provenance.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="recall_text_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="sha256 of normalised question text — used for cross-PDF dedup.",
                max_length=64,
            ),
        ),
    ]
