# Generated by Django 5.2.12 on 2026-07-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0025_questionimage_admin_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("cms", "UPSC CMS"),
                    ("neet_pg", "NEET PG"),
                    ("ini_cet", "INI-CET"),
                    ("usmle", "USMLE"),
                    ("fmge", "FMGE"),
                ],
                default="cms",
                help_text="Target exam for this subject",
                max_length=20,
            ),
        ),
    ]
