# Generated by Django 5.2.12 on 2026-07-29 15:34
# Hand-edited: the auto-generated AddField for `updated_at` would crash on
# production Postgres because the column was already added ad-hoc (and
# migration 0028 was a no-op for the same reason). We replace the
# AddField with the same idempotent RunPython pattern that 0028 uses,
# so re-running this migration on an already-current schema is safe.
# The CreateModel for `RemovedQuestion` is left untouched.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# ---- idempotent add for QuestionImage.updated_at ----------------------------
TABLE = "questions_questionimage"
COLUMN = "updated_at"


def _has_column(schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == "postgresql":
            cursor.execute(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_name = %s AND column_name = %s",
                [TABLE, COLUMN],
            )
        else:
            cursor.execute(
                "SELECT 1 FROM pragma_table_info(%s) WHERE name = %s",
                [TABLE, COLUMN],
            )
        return cursor.fetchone() is not None


def _add_field_if_missing(apps, schema_editor):
    if _has_column(schema_editor):
        return
    field = models.DateTimeField(auto_now=True)
    field.set_attributes_from_name(COLUMN)
    schema_editor.add_field(apps.get_model("questions", "QuestionImage"), field)


def _drop_field_if_present(apps, schema_editor):
    if not _has_column(schema_editor):
        return
    model = apps.get_model("questions", "QuestionImage")
    schema_editor.remove_field(model, model._meta.get_field(COLUMN))


# ----------------------------------------------------------------------------


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0032_split_space_joined_stems"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_add_field_if_missing, _drop_field_if_present),
        migrations.CreateModel(
            name="RemovedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_source", models.CharField(db_index=True, max_length=80)),
                ("year", models.IntegerField(blank=True, db_index=True, null=True)),
                ("source_number", models.IntegerField(blank=True, null=True)),
                ("question_text_hash", models.CharField(db_index=True, max_length=64)),
                ("original_question_id", models.IntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("removed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="removed_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-removed_at"],
                "indexes": [
                    models.Index(
                        fields=["exam_source", "year", "source_number"],
                        name="questions_r_exam_so_543edf_idx",
                    ),
                    models.Index(
                        fields=["question_text_hash"],
                        name="questions_r_questio_c597b9_idx",
                    ),
                ],
            },
        ),
    ]
