# Generated by Django 5.2.12 on 2026-07-29 20:08
#
# Hand-edited: the auto-generated AddField would crash because migration 0033
# already added the `updated_at` column on production Postgres via its
# idempotent RunPython helper. Re-running AddField here would re-issue
# `ALTER TABLE ... ADD COLUMN updated_at ...` and fail with
# `column "updated_at" of relation "questions_questionimage" already exists`.
#
# This migration is therefore STATE-ONLY: it tells Django's migration state
# about the field (so makemigrations stops complaining) without issuing any
# SQL on the database. The column itself was added by migration 0033.

from django.db import migrations, models


# State-only AddField — Django's migration framework treats `migrations.AddField`
# as a "schema_forwards"/"state_forwards" pair. By overriding the schema
# methods to no-op, we still update Django's internal state (so future
# makemigrations won't re-add it) without issuing SQL on the DB.
class StateOnlyAddField(migrations.AddField):
    """AddField that only updates Django state — does not touch the DB."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # The column already exists (created by migration 0033). Skip the SQL.
        pass

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # Reversal must also be a no-op — we never added the column.
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0033_questionimage_updated_at_removedquestion"),
    ]

    operations = [
        StateOnlyAddField(
            model_name="questionimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]