# Generated by Django 5.2.12 on 2026-09-21 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0037_questionimage_strict_explanation_fix"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "content",
                    models.TextField(help_text="Markdown-formatted note content."),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("cms", "UPSC CMS"),
                            ("neet_pg", "NEET PG"),
                            ("ini_cet", "INICET"),
                            ("usmle", "USMLE"),
                            ("fmge", "FMGE"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="cms",
                        max_length=20,
                    ),
                ),
                (
                    "is_combined",
                    models.BooleanField(
                        default=False,
                        help_text="True when this note covers the same topic across multiple exams.",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AlterField(
            model_name="questionbookmark",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(
                fields=["question", "parent", "is_pinned"],
                name="questions_d_questio_b10e42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="flashcard",
            index=models.Index(
                fields=["user", "next_review"], name="questions_f_user_id_175846_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flashcard",
            index=models.Index(
                fields=["user", "subject"], name="questions_f_user_id_c7d3ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["is_active", "exam_type"], name="questions_q_is_acti_6b55e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["exam_type", "year"], name="questions_q_exam_ty_c8f63f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["exam_track", "is_active", "year"],
                name="questions_q_exam_tr_e4c4cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["created_at"], name="questions_q_created_d1d888_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["subject", "is_active", "difficulty"],
                name="questions_q_subject_6acde9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["topic", "is_active"], name="questions_q_topic_i_ad798a_idx"
            ),
        ),
        migrations.AddField(
            model_name="topicnote",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_topic_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="topicnote",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="topic_notes",
                to="questions.subject",
            ),
        ),
        migrations.AddField(
            model_name="topicnote",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="topic_notes",
                to="questions.topic",
            ),
        ),
        migrations.AddIndex(
            model_name="topicnote",
            index=models.Index(
                fields=["subject", "exam_type", "is_active"],
                name="questions_t_subject_53b0a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="topicnote",
            index=models.Index(
                fields=["topic", "is_active"], name="questions_t_topic_i_e40548_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="topicnote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("topic__isnull", False)),
                fields=("topic", "exam_type", "is_combined"),
                name="uniq_topic_note",
            ),
        ),
    ]
