# Generated by Django 5.2.12 on 2026-09-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0038_topicnote_create"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="why_correct",
            field=models.TextField(
                blank=True, help_text="Why the selected correct answer is right"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="why_wrong_a",
            field=models.TextField(blank=True, help_text="Why option A is wrong"),
        ),
        migrations.AddField(
            model_name="question",
            name="why_wrong_b",
            field=models.TextField(blank=True, help_text="Why option B is wrong"),
        ),
        migrations.AddField(
            model_name="question",
            name="why_wrong_c",
            field=models.TextField(blank=True, help_text="Why option C is wrong"),
        ),
        migrations.AddField(
            model_name="question",
            name="why_wrong_d",
            field=models.TextField(blank=True, help_text="Why option D is wrong"),
        ),
    ]
