# Generated by Django 5.2.12 on 2026-07-20 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_engine",
            "0002_rename_ai_engine_c_session_a6c7f8_idx_ai_engine_c_session_b8fb58_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query",
                    models.TextField(help_text="The prompt or query sent to the AI"),
                ),
                (
                    "response_text",
                    models.TextField(help_text="The AI response that is being rated"),
                ),
                ("is_helpful", models.BooleanField(default=True)),
                (
                    "report_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason if reported (e.g. incorrect, inappropriate)",
                        max_length=255,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="ai_engine.chatmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
