# Generated by Django 5.2.12 on 2026-08-02 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0004_aitutordailyusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitutordailyusage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="aitutordailyusage",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
