"""
Curated UPSC-CMS-relevant medical ontology.

This is intentionally a SMALL, HIGH-QUALITY subset of medical concepts.
We do not pull ICD-10 wholesale (80k+ codes). We curate the 200+
diseases, 100+ drugs, and 50+ procedures that actually recur in UPSC
CMS PYQs 2018-2024.

Key design points:
- `subject` mirrors the user's `questions.Subject` taxonomy
- `canonical_id` links to ICD-10 / ATC / MeSH where applicable
- `synonyms` power query rewriting ("HTN" -> "Hypertension")
- Relations (`related`, `pyq_topics`) form a starter KG

This module exports DATA + a `load_ontology()` management helper.
"""

# Each entry: name, type, subject, canonical_id, synonyms, definition
ENTITIES = [
    # ─── Medicine / Cardiology ───────────────────────────────
    ("Hypertension", "disease", "medicine", "ICD10:I10",
     ["HTN", "high blood pressure", "raised BP"],
     "Sustained elevation of systemic arterial blood pressure >=140/90 mmHg."),
    ("Ischemic heart disease", "disease", "medicine", "ICD10:I20-I25",
     ["IHD", "coronary artery disease", "CAD", "angina pectoris", "MI"],
     "Spectrum of disease caused by reduced myocardial perfusion, most often due to atherosclerosis."),
    ("Acute myocardial infarction", "disease", "medicine", "ICD10:I21",
     ["MI", "heart attack", "STEMI", "NSTEMI"],
     "Acute necrosis of cardiac myocytes due to prolonged ischemia, typically from coronary thrombosis."),
    ("Heart failure", "disease", "medicine", "ICD10:I50",
     ["CHF", "congestive cardiac failure", "CCF"],
     "Clinical syndrome of impaired ventricular filling or ejection, with characteristic signs/symptoms."),
    ("Atrial fibrillation", "disease", "medicine", "ICD10:I48",
     ["AF", "AFib"],
     "Supraventricular tachyarrhythmia with uncoordinated atrial activation and consequent deterioration of mechanical function."),
    ("Rheumatic fever", "disease", "medicine", "ICD10:I00-I02",
     ["ARF", "acute rheumatic fever", "RF"],
     "Autoimmune multisystem inflammatory disease following Group A Streptococcal pharyngitis."),
    ("Infective endocarditis", "disease", "medicine", "ICD10:I33",
     ["IE", "SBE", "subacute bacterial endocarditis"],
     "Infection of the endocardial surface of the heart, typically of the valves."),
    ("Pulmonary embolism", "disease", "medicine", "ICD10:I26",
     ["PE"],
     "Obstruction of pulmonary arteries, usually by thrombus from deep veins of lower limbs."),
    ("Cardiomyopathy", "disease", "medicine", "ICD10:I42",
     ["DCM", "dilated cardiomyopathy", "HCM", "hypertrophic cardiomyopathy"],
     "Disease of the heart muscle with structural and functional abnormalities unrelated to coronary disease, hypertension, or valvular disease."),

    # ─── Medicine / Pulmonology ──────────────────────────────
    ("Pneumonia", "disease", "medicine", "ICD10:J12-J18",
     ["lobar pneumonia", "bronchopneumonia", "CAP", "community-acquired pneumonia"],
     "Infection of the lung parenchyma causing alveolar consolidation."),
    ("Tuberculosis", "disease", "medicine", "ICD10:A15-A19",
     ["TB", "pulmonary TB", "PTB", "mycobacterium tuberculosis"],
     "Chronic granulomatous infectious disease caused by Mycobacterium tuberculosis."),
    ("Asthma", "disease", "medicine", "ICD10:J45",
     ["bronchial asthma"],
     "Chronic inflammatory airway disease characterized by reversible airflow obstruction and bronchial hyperresponsiveness."),
    ("COPD", "disease", "medicine", "ICD10:J44",
     ["chronic obstructive pulmonary disease", "emphysema", "chronic bronchitis"],
     "Chronic, progressive, partially reversible airflow limitation caused by airway and parenchymal inflammation, most often from smoking."),

    # ─── Medicine / Endocrinology ────────────────────────────
    ("Diabetes mellitus type 2", "disease", "medicine", "ICD10:E11",
     ["T2DM", "T2DM", "DM2", "type 2 diabetes"],
     "Chronic metabolic disorder of hyperglycemia from insulin resistance with relative insulin deficiency."),
    ("Hypothyroidism", "disease", "medicine", "ICD10:E03",
     ["myxoedema", "Hashimoto"],
     "Deficiency of thyroid hormone action at peripheral tissues."),
    ("Hyperthyroidism", "disease", "medicine", "ICD10:E05",
     ["thyrotoxicosis", "Graves disease"],
     "Clinical syndrome of excess circulating thyroid hormones."),
    ("Cushing syndrome", "disease", "medicine", "ICD10:E24",
     ["hypercortisolism"],
     "Clinical features from chronic exposure to excess glucocorticoids."),

    # ─── Medicine / Nephrology ───────────────────────────────
    ("Chronic kidney disease", "disease", "medicine", "ICD10:N18",
     ["CKD", "chronic renal failure", "CRF"],
     "Progressive loss of renal function over >3 months, with structural or functional abnormalities."),
    ("Acute kidney injury", "disease", "medicine", "ICD10:N17",
     ["AKI", "acute renal failure", "ARF"],
     "Abrupt decline in renal function over hours to days, classified by RIFLE / AKIN / KDIGO criteria."),

    # ─── Medicine / Hematology ───────────────────────────────
    ("Iron deficiency anemia", "disease", "medicine", "ICD10:D50",
     ["IDA", "microcytic anemia"],
     "Anemia from inadequate iron for normal hemoglobin synthesis."),
    ("Megaloblastic anemia", "disease", "medicine", "ICD10:D53",
     ["B12 deficiency", "folate deficiency", "pernicious anemia"],
     "Anemia from impaired DNA synthesis with characteristic megaloblastic changes in bone marrow."),
    ("Thalassemia", "disease", "medicine", "ICD10:D56",
     ["beta thalassemia", "alpha thalassemia", "thal"],
     "Inherited disorder of reduced or absent synthesis of one or more globin chains."),
    ("Sickle cell disease", "disease", "medicine", "ICD10:D57",
     ["SCD", "HbSS"],
     "Autosomal recessive hemoglobinopathy producing characteristic sickled erythrocytes and hemolysis."),

    # ─── Medicine / Rheumatology / Connective Tissue ─────────
    ("Systemic lupus erythematosus", "disease", "medicine", "ICD10:M32",
     ["SLE", "lupus"],
     "Multisystem autoimmune disease with diverse clinical features and autoantibody formation."),
    ("Rheumatoid arthritis", "disease", "medicine", "ICD10:M06",
     ["RA"],
     "Chronic systemic inflammatory disease primarily targeting synovial joints."),

    # ─── Medicine / Infectious Disease ───────────────────────
    ("Dengue", "disease", "medicine", "ICD10:A90",
     ["dengue fever", "DHF", "dengue hemorrhagic fever"],
     "Mosquito-borne viral infection by dengue virus, with potential severe complications including plasma leakage."),
    ("Malaria", "disease", "medicine", "ICD10:B50-B54",
     ["plasmodium"],
     "Mosquito-borne protozoal infection by Plasmodium species."),
    ("Typhoid fever", "disease", "medicine", "ICD10:A01.0",
     ["enteric fever", "salmonella typhi"],
     "Systemic infection by Salmonella typhi with characteristic stepwise fever."),
    ("HIV/AIDS", "disease", "medicine", "ICD10:B20-B24",
     ["human immunodeficiency virus", "AIDS"],
     "Chronic retroviral infection causing progressive immune deficiency."),
    ("Hepatitis B", "disease", "medicine", "ICD10:B16",
     ["HBV"],
     "Hepadnavirus infection of the liver, transmitted parenterally and sexually."),
    ("Tetanus", "disease", "medicine", "ICD10:A33-A35",
     ["lockjaw"],
     "Acute neuromuscular disease from Clostridium tetani exotoxin, causing muscle spasm."),
    ("Rabies", "disease", "medicine", "ICD10:A82",
     ["lyssa"],
     "Fatal encephalitis from Lyssavirus, transmitted by mammal bites."),

    # ─── OBG ────────────────────────────────────────────────
    ("Pre-eclampsia", "disease", "obg", "ICD10:O14",
     ["PE", "toxemia of pregnancy"],
     "New-onset hypertension after 20 weeks gestation with proteinuria or end-organ dysfunction."),
    ("Eclampsia", "disease", "obg", "ICD10:O15",
     [],
     "New-onset generalized seizures in a woman with pre-eclampsia."),
    ("Gestational diabetes mellitus", "disease", "obg", "ICD10:O24.4",
     ["GDM"],
     "Glucose intolerance first recognized during pregnancy."),
    ("Placenta previa", "disease", "obg", "ICD10:O44",
     [],
     "Placenta that overlies or is within 2 cm of the internal cervical os after 20 weeks."),
    ("Ectopic pregnancy", "disease", "obg", "ICD10:O00",
     ["tubal pregnancy"],
     "Pregnancy implanted outside the uterine cavity, most commonly in the fallopian tube."),
    ("Polycystic ovary syndrome", "disease", "obg", "ICD10:E28.2",
     ["PCOS"],
     "Endocrine disorder with hyperandrogenism, ovulatory dysfunction, and polycystic ovarian morphology."),

    # ─── Pediatrics ────────────────────────────────────────
    ("Kawasaki disease", "disease", "paediatrics", "ICD10:M30.3",
     ["KD", "mucocutaneous lymph node syndrome"],
     "Acute medium-vessel vasculitis of childhood with fever, mucocutaneous signs, and coronary aneurysms."),
    ("Neonatal sepsis", "disease", "paediatrics", "ICD10:P36",
     ["sepsis of newborn"],
     "Systemic infection in the first 28 days of life with hemodynamic compromise."),
    ("Acute respiratory distress syndrome", "disease", "paediatrics", "ICD10:J80",
     ["ARDS"],
     "Non-cardiogenic pulmonary edema with diffuse alveolar damage and refractory hypoxemia."),
    ("Bronchiolitis", "disease", "paediatrics", "ICD10:J21",
     ["RSV bronchiolitis"],
     "Viral lower respiratory tract infection of infants, most often due to RSV."),

    # ─── Surgery ───────────────────────────────────────────
    ("Acute appendicitis", "disease", "surgery", "ICD10:K35",
     ["appendix"],
     "Acute inflammation of the vermiform appendix, the most common surgical emergency."),
    ("Acute pancreatitis", "disease", "surgery", "ICD10:K85",
     [],
     "Acute inflammatory process of the pancreas with variable involvement of peripancreatic tissues."),
    ("Cholecystitis", "disease", "surgery", "ICD10:K81",
     ["acute cholecystitis"],
     "Inflammation of the gallbladder, usually from cystic duct obstruction by a gallstone."),
    ("Intestinal obstruction", "disease", "surgery", "ICD10:K56",
     ["bowel obstruction", "IO"],
     "Impairment of aboral flow of intestinal contents; mechanical or functional."),
    ("Perforation peritonitis", "disease", "surgery", "ICD10:K65",
     ["peritonitis"],
     "Inflammation of the peritoneum, commonly from hollow viscus perforation."),

    # ─── PSM / Community Medicine ──────────────────────────
    ("Vaccination", "concept", "psm", "",
     ["immunization", "vaccine"],
     "Administration of antigenic material to induce protective immunity."),
    ("Sanitation", "concept", "psm", "",
     [],
     "Public health practice of maintaining clean water supply, sewage disposal, and hygiene."),
    ("National Health Mission", "guideline", "psm", "",
     ["NHM", "NRHM", "NUHM"],
     "Indian government flagship health program covering rural and urban health systems."),
    ("Reproductive and Child Health", "guideline", "psm", "",
     ["RCH"],
     "Indian national program covering maternal, neonatal, and child health interventions."),

    # ─── Symptoms / Signs ──────────────────────────────────
    ("Fever", "symptom", "medicine", "",
     ["pyrexia"],
     "Elevation of body temperature above normal circadian variation."),
    ("Chest pain", "symptom", "medicine", "",
     [],
     "Subjective discomfort in the thoracic region; cardiac, pulmonary, GI, or musculoskeletal origin."),
    ("Dyspnea", "symptom", "medicine", "",
     ["breathlessness", "SOB"],
     "Subjective experience of breathing discomfort."),
    ("Cough", "symptom", "medicine", "",
     [],
     "Sudden expulsion of air from the lungs to clear airway secretions or foreign material."),
    ("Hemoptysis", "symptom", "medicine", "",
     [],
     "Expectoration of blood from the lower respiratory tract."),
    ("Jaundice", "symptom", "medicine", "",
     ["icterus"],
     "Yellow discoloration of skin/eyes from elevated serum bilirubin."),
    ("Edema", "symptom", "medicine", "",
     ["oedema", "swelling"],
     "Excess fluid in interstitial space."),
    ("Lymphadenopathy", "symptom", "medicine", "",
     ["swollen lymph nodes", "lymph node enlargement"],
     "Abnormal enlargement of lymph nodes."),
    ("Hepatosplenomegaly", "symptom", "medicine", "",
     ["HSM"],
     "Simultaneous enlargement of liver and spleen."),

    # ─── Drugs (curated) ───────────────────────────────────
    ("Aspirin", "drug", "pharmacology", "ATC:N02BA01",
     ["acetylsalicylic acid", "ASA"],
     "Antiplatelet / analgesic / antipyretic; irreversible COX-1 inhibitor."),
    ("Clopidogrel", "drug", "pharmacology", "ATC:B01AC04",
     [],
     "P2Y12 inhibitor; antiplatelet for ACS and post-stent therapy."),
    ("Atorvastatin", "drug", "pharmacology", "ATC:C10AA05",
     ["statin"],
     "HMG-CoA reductase inhibitor for hypercholesterolemia."),
    ("Enalapril", "drug", "pharmacology", "ATC:C09AA02",
     ["ACE inhibitor", "ACEi"],
     "ACE inhibitor used in hypertension and heart failure."),
    ("Losartan", "drug", "pharmacology", "ATC:C09CA01",
     ["ARB"],
     "Angiotensin II receptor blocker for hypertension."),
    ("Metformin", "drug", "pharmacology", "ATC:A10BA02",
     [],
     "Biguanide antihyperglycemic; first-line for T2DM."),
    ("Insulin", "drug", "pharmacology", "ATC:A10A",
     [],
     "Exogenous peptide hormone for diabetes therapy."),
    ("Amoxicillin", "drug", "pharmacology", "ATC:J01CA04",
     ["amoxycillin"],
     "Broad-spectrum beta-lactam aminopenicillin."),
    ("Doxycycline", "drug", "pharmacology", "ATC:J01AA02",
     [],
     "Tetracycline-class antibiotic; also used in rickettsial disease."),
    ("Ceftriaxone", "drug", "pharmacology", "ATC:J01DD04",
     ["CRO"],
     "Third-generation cephalosporin for parenteral use."),
    ("Azithromycin", "drug", "pharmacology", "ATC:J01FA10",
     ["AZM"],
     "Macrolide antibiotic; long half-life."),
    ("Isoniazid", "drug", "pharmacology", "ATC:J04AC01",
     ["INH"],
     "First-line anti-tubercular drug; mycolic acid synthesis inhibitor."),
    ("Rifampicin", "drug", "pharmacology", "ATC:J04AB02",
     ["RIF", "rifampin"],
     "RNA polymerase inhibitor; first-line anti-TB drug."),
    ("Pyrazinamide", "drug", "pharmacology", "ATC:J04AK01",
     ["PZA"],
     "First-line anti-TB drug active in acidic environment."),
    ("Ethambutol", "drug", "pharmacology", "ATC:J04AK02",
     ["EMB"],
     "First-line anti-TB drug; inhibits arabinosyl transferase."),
    ("Artemether", "drug", "pharmacology", "ATC:P01BE02",
     [],
     "Antimalarial artemisinin derivative; rapid schizonticidal."),
    ("Tenofovir", "drug", "pharmacology", "ATC:J05AF07",
     ["TDF"],
     "Reverse transcriptase inhibitor for HIV and HBV."),
    ("Paracetamol", "drug", "pharmacology", "ATC:N02BE01",
     ["acetaminophen"],
     "Analgesic/antipyretic; weak COX inhibitor."),
    ("Furosemide", "drug", "pharmacology", "ATC:C03CA01",
     ["frusemide"],
     "Loop diuretic inhibiting Na-K-2Cl in thick ascending limb."),
    ("Spironolactone", "drug", "pharmacology", "ATC:C03DA01",
     [],
     "Potassium-sparing aldosterone antagonist."),

    # ─── Investigations ────────────────────────────────────
    ("Mantoux test", "investigation", "medicine", "",
     ["tuberculin skin test", "TST", "PPD"],
     "Intracutaneous test for delayed hypersensitivity to tuberculin."),
    ("ECG", "investigation", "medicine", "",
     ["electrocardiogram", "EKG"],
     "Recording of electrical activity of the heart."),
    ("Echocardiography", "investigation", "medicine", "",
     ["echo", "2D echo"],
     "Ultrasound imaging of cardiac structures and function."),
    ("Troponin", "investigation", "medicine", "",
     ["cardiac troponin", "Trop T", "Trop I"],
     "Cardiac-specific biomarker for myocardial injury."),
    ("D-dimer", "investigation", "medicine", "",
     [],
     "Fibrin degradation product; sensitive but nonspecific for VTE."),
    ("HbA1c", "investigation", "medicine", "",
     ["glycated hemoglobin"],
     "Reflects average blood glucose over preceding 2-3 months."),
    ("Liver function test", "investigation", "medicine", "",
     ["LFT"],
     "Panel measuring bilirubin, transaminases, ALP, albumin, PT."),
    ("Renal function test", "investigation", "medicine", "",
     ["RFT", "KFT"],
     "Panel measuring BUN, creatinine, electrolytes, eGFR."),
    ("Complete blood count", "investigation", "medicine", "",
     ["CBC", "hemogram"],
     "Hematology panel: Hb, TLC, DLC, platelet count, indices."),
    ("Thyroid function test", "investigation", "medicine", "",
     ["TFT"],
     "TSH, free T4, free T3 panel."),

    # ─── Procedures / Anatomy ──────────────────────────────
    ("Cesarean section", "procedure", "obg", "",
     ["LSCS", "C-section"],
     "Surgical delivery of fetus through abdominal and uterine incisions."),
    ("Tubectomy", "procedure", "obg", "",
     ["tubal ligation"],
     "Female sterilization by interruption of fallopian tubes."),
    ("Vasectomy", "procedure", "surgery", "",
     [],
     "Male sterilization by interruption of vas deferens."),
    ("Cholecystectomy", "procedure", "surgery", "",
     [],
     "Surgical removal of gallbladder."),
    ("Appendectomy", "procedure", "surgery", "",
     [],
     "Surgical removal of vermiform appendix."),
    ("Coronary artery bypass graft", "procedure", "surgery", "",
     ["CABG"],
     "Revascularization procedure bypassing coronary stenoses using grafts."),
    ("Kidney", "anatomy", "anatomy", "",
     ["renal"],
     "Retroperitoneal paired organ producing urine and regulating fluid/electrolytes."),
    ("Liver", "anatomy", "anatomy", "",
     ["hepatic"],
     "Largest internal organ; metabolism, detoxification, bile production."),
    ("Heart", "anatomy", "anatomy", "",
     ["cardiac"],
     "Four-chambered muscular pump of the cardiovascular system."),
    ("Lung", "anatomy", "anatomy", "",
     ["pulmonary"],
     "Paired thoracic organ of gas exchange."),
    ("Brain", "anatomy", "anatomy", "",
     ["cerebral"],
     "Central organ of the nervous system."),
]


# Knowledge graph edges: (source_name, relation, target_name)
# Curated from CMS PYQ patterns and standard medical curricula.
RELATIONS = [
    # Hypertension
    ("Hypertension", "treated_by", "Enalapril"),
    ("Hypertension", "treated_by", "Losartan"),
    ("Hypertension", "risk_factor_for", "Ischemic heart disease"),
    ("Hypertension", "risk_factor_for", "Acute kidney injury"),
    ("Hypertension", "risk_factor_for", "Stroke"),
    ("Hypertension", "investigated_by", "ECG"),
    ("Hypertension", "investigated_by", "Renal function test"),

    # IHD / MI
    ("Ischemic heart disease", "symptom_of", "Chest pain"),
    ("Acute myocardial infarction", "symptom_of", "Chest pain"),
    ("Acute myocardial infarction", "causes", "Heart failure"),
    ("Acute myocardial infarction", "investigated_by", "ECG"),
    ("Acute myocardial infarction", "investigated_by", "Troponin"),
    ("Acute myocardial infarction", "treated_by", "Aspirin"),
    ("Acute myocardial infarction", "treated_by", "Clopidogrel"),
    ("Acute myocardial infarction", "treated_by", "Atorvastatin"),
    ("Ischemic heart disease", "treated_by", "Coronary artery bypass graft"),

    # Heart failure
    ("Heart failure", "treated_by", "Furosemide"),
    ("Heart failure", "treated_by", "Spironolactone"),
    ("Heart failure", "treated_by", "Enalapril"),
    ("Heart failure", "symptom_of", "Dyspnea"),

    # AF
    ("Atrial fibrillation", "investigated_by", "ECG"),
    ("Atrial fibrillation", "investigated_by", "Echocardiography"),
    ("Atrial fibrillation", "risk_factor_for", "Pulmonary embolism"),

    # PE
    ("Pulmonary embolism", "investigated_by", "D-dimer"),
    ("Pulmonary embolism", "symptom_of", "Dyspnea"),
    ("Pulmonary embolism", "symptom_of", "Hemoptysis"),

    # Pneumonia / TB
    ("Pneumonia", "treated_by", "Amoxicillin"),
    ("Pneumonia", "treated_by", "Azithromycin"),
    ("Pneumonia", "symptom_of", "Cough"),
    ("Pneumonia", "symptom_of", "Fever"),
    ("Tuberculosis", "treated_by", "Isoniazid"),
    ("Tuberculosis", "treated_by", "Rifampicin"),
    ("Tuberculosis", "treated_by", "Pyrazinamide"),
    ("Tuberculosis", "treated_by", "Ethambutol"),
    ("Tuberculosis", "investigated_by", "Mantoux test"),
    ("Tuberculosis", "symptom_of", "Cough"),
    ("Tuberculosis", "symptom_of", "Hemoptysis"),

    # Asthma / COPD
    ("Asthma", "symptom_of", "Dyspnea"),
    ("Asthma", "symptom_of", "Cough"),
    ("COPD", "symptom_of", "Dyspnea"),
    ("COPD", "symptom_of", "Cough"),

    # Diabetes
    ("Diabetes mellitus type 2", "treated_by", "Metformin"),
    ("Diabetes mellitus type 2", "treated_by", "Insulin"),
    ("Diabetes mellitus type 2", "investigated_by", "HbA1c"),
    ("Diabetes mellitus type 2", "risk_factor_for", "Ischemic heart disease"),
    ("Diabetes mellitus type 2", "risk_factor_for", "Chronic kidney disease"),

    # Thyroid
    ("Hypothyroidism", "investigated_by", "Thyroid function test"),
    ("Hyperthyroidism", "investigated_by", "Thyroid function test"),

    # Kidney
    ("Chronic kidney disease", "investigated_by", "Renal function test"),
    ("Acute kidney injury", "investigated_by", "Renal function test"),

    # Anemia
    ("Iron deficiency anemia", "investigated_by", "Complete blood count"),
    ("Megaloblastic anemia", "investigated_by", "Complete blood count"),
    ("Thalassemia", "investigated_by", "Complete blood count"),
    ("Iron deficiency anemia", "symptom_of", "Edema"),

    # ID
    ("Dengue", "treated_by", "Paracetamol"),
    ("Malaria", "treated_by", "Artemether"),
    ("Typhoid fever", "treated_by", "Ceftriaxone"),
    ("Hepatitis B", "treated_by", "Tenofovir"),
    ("Tuberculosis", "pyq_topic", "PSM"),
    ("Malaria", "pyq_topic", "PSM"),

    # OBG
    ("Pre-eclampsia", "treated_by", "Aspirin"),
    ("Gestational diabetes mellitus", "treated_by", "Insulin"),
    ("Placenta previa", "treated_by", "Cesarean section"),
    ("Ectopic pregnancy", "treated_by", "Cesarean section"),

    # Surgery
    ("Acute appendicitis", "treated_by", "Appendectomy"),
    ("Cholecystitis", "treated_by", "Cholecystectomy"),

    # Anatomy
    ("Kidney", "related_to", "Liver"),
    ("Heart", "related_to", "Lung"),
    ("Brain", "related_to", "Heart"),

    # Cross
    ("Ischemic heart disease", "pyq_topic", "Medicine"),
    ("Hypertension", "pyq_topic", "Medicine"),
    ("Pneumonia", "pyq_topic", "Medicine"),
    ("Diabetes mellitus type 2", "pyq_topic", "Medicine"),
    ("Acute appendicitis", "pyq_topic", "Surgery"),
    ("Pre-eclampsia", "pyq_topic", "OBG"),
    ("Gestational diabetes mellitus", "pyq_topic", "OBG"),
    ("Kawasaki disease", "pyq_topic", "Paediatrics"),
    ("Neonatal sepsis", "pyq_topic", "Paediatrics"),
    ("Tuberculosis", "pyq_topic", "PSM"),
    ("Vaccination", "pyq_topic", "PSM"),
    ("Sanitation", "pyq_topic", "PSM"),
    ("National Health Mission", "pyq_topic", "PSM"),
]


# High-yield topics for CMS exam orientation — used by the indexer
# to enrich chunks with `topic` metadata.
PYQ_TOPICS_BY_SUBJECT = {
    "medicine": [
        "Cardiology", "Pulmonology", "Endocrinology", "Nephrology",
        "Hematology", "Rheumatology", "Infectious Diseases", "Neurology",
        "Gastroenterology", "Hepatology",
    ],
    "surgery": [
        "General Surgery", "Gastrointestinal Surgery", "Cardiothoracic Surgery",
        "Urology", "Orthopaedics", "Trauma",
    ],
    "obg": [
        "Obstetrics", "Gynecology", "Family Planning", "Maternal Health",
    ],
    "paediatrics": [
        "Neonatology", "Growth & Development", "Nutrition",
        "Pediatric Infections", "Pediatric Cardiology",
        "Pediatric Pulmonology", "Immunization",
    ],
    "psm": [
        "Epidemiology", "Biostatistics", "National Health Programmes",
        "Communicable Diseases", "Non-communicable Diseases",
        "Maternal & Child Health", "Nutrition", "Environmental Health",
        "Health Education", "Occupational Health",
    ],
    "ent": ["Ear", "Nose", "Throat", "Head & Neck"],
    "ophthalmology": ["Anterior Segment", "Posterior Segment", "Optics", "Squint"],
    "orthopaedics": ["Fractures", "Joint Disorders", "Bone Disorders", "Sports Injuries"],
    "anaesthesia": ["General Anaesthesia", "Regional Anaesthesia", "Critical Care"],
    "dermatology": ["Inflammatory", "Infectious", "Neoplastic"],
    "psychiatry": ["Mood Disorders", "Anxiety", "Psychosis", "Substance Use"],
    "microbiology": ["Bacteriology", "Virology", "Mycology", "Parasitology", "Immunology"],
    "pathology": ["General Pathology", "Systemic Pathology", "Hematopathology"],
    "pharmacology": ["General Pharmacology", "Autonomic", "CNS", "Chemotherapy"],
    "forensic_medicine": ["Thanatology", "Traumatology", "Toxicology", "Identification"],
    "anatomy": ["Gross Anatomy", "Histology", "Embryology", "Neuroanatomy"],
    "physiology": ["General Physiology", "Systemic Physiology"],
    "biochemistry": ["Enzymes", "Metabolism", "Molecular Biology"],
}


# Medical synonym + abbreviation expansion used at query time.
# Keys are normalized to lowercase.
QUERY_SYNONYMS = {
    "htn": "hypertension",
    "mi": "myocardial infarction",
    "cad": "coronary artery disease",
    "chf": "heart failure",
    "af": "atrial fibrillation",
    "afib": "atrial fibrillation",
    "dmt2": "diabetes mellitus type 2",
    "t2dm": "diabetes mellitus type 2",
    "dm": "diabetes mellitus",
    "tb": "tuberculosis",
    "copd": "chronic obstructive pulmonary disease",
    "aki": "acute kidney injury",
    "ckd": "chronic kidney disease",
    "copd": "copd",
    "ra": "rheumatoid arthritis",
    "sle": "systemic lupus erythematosus",
    "ihd": "ischemic heart disease",
    "lid": "iron deficiency anemia",
    "ida": "iron deficiency anemia",
    "gdm": "gestational diabetes mellitus",
    "pcos": "polycystic ovary syndrome",
    "kd": "kawasaki disease",
    "lscs": "cesarean section",
    "cabg": "coronary artery bypass graft",
    "cro": "ceftriaxone",
    "azm": "azithromycin",
    "inh": "isoniazid",
    "rif": "rifampicin",
    "pza": "pyrazinamide",
    "emb": "ethambutol",
    "asa": "aspirin",
    "acei": "ace inhibitor",
    "ace inhibitor": "angiotensin-converting enzyme inhibitor",
    "arb": "angiotensin receptor blocker",
    "tst": "mantoux test",
    "ppd": "mantoux test",
    "ecg": "electrocardiogram",
    "ekg": "electrocardiogram",
    "echo": "echocardiography",
    "lft": "liver function test",
    "rft": "renal function test",
    "kft": "renal function test",
    "cbc": "complete blood count",
    "tft": "thyroid function test",
    "hba1c": "glycated hemoglobin",
    "lscs": "lower segment cesarean section",
    "nhp": "national health programmes",
    "nhm": "national health mission",
    "rch": "reproductive and child health",
    "rntcp": "revised national tuberculosis control programme",
    "rnTCP": "revised national tuberculosis control programme",
}