# Generated by Django 5.2.12 on 2026-08-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("excerpt", models.TextField()),
                (
                    "cover_image",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("category", models.CharField(db_index=True, max_length=100)),
                (
                    "subcategory",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "author_id",
                    models.CharField(default="crackcms-editorial", max_length=200),
                ),
                (
                    "reviewed_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("author", models.CharField(max_length=200)),
                ("author_role", models.CharField(max_length=200)),
                ("date_published", models.CharField(max_length=50)),
                (
                    "date_modified",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("updated_at", models.CharField(blank=True, default="", max_length=50)),
                ("reading_time", models.CharField(default="10 min", max_length=20)),
                (
                    "word_count",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("primary_cta", models.JSONField(blank=True, default=dict)),
                ("related_exam_paths", models.JSONField(blank=True, default=list)),
                ("faqs", models.JSONField(blank=True, default=list)),
                ("toc", models.JSONField(blank=True, default=list)),
                ("references", models.JSONField(blank=True, default=list)),
                ("revision_log", models.JSONField(blank=True, default=list)),
                ("body", models.TextField()),
                ("prelude", models.TextField(blank=True, default="")),
                ("outro", models.TextField(blank=True, default="")),
                ("pinned", models.BooleanField(default=False)),
                ("trending", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-date_published", "-created_at"],
            },
        ),
    ]
