# Generated by Django 5.2.12 on 2026-03-03 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("subject", "Subject-wise Test"),
                            ("topic", "Topic-wise Micro Test"),
                            ("mixed", "Mixed Practice Test"),
                            ("paper1", "Full Paper 1 Mock"),
                            ("paper2", "Full Paper 2 Mock"),
                            ("daily", "Daily Quick Test"),
                            ("pyq_year", "Previous Year Paper"),
                            ("weak", "Weak Topic Test"),
                            ("adaptive", "AI Adaptive Test"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("num_questions", models.IntegerField(default=20)),
                (
                    "time_limit_minutes",
                    models.IntegerField(default=30, help_text="Time limit in minutes"),
                ),
                ("negative_marking", models.BooleanField(default=True)),
                ("negative_mark_value", models.FloatField(default=0.33)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        blank=True, related_name="tests", to="questions.question"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tests",
                        to="questions.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tests",
                        to="questions.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("total_marks", models.FloatField(blank=True, null=True)),
                ("correct_count", models.IntegerField(default=0)),
                ("incorrect_count", models.IntegerField(default=0)),
                ("unanswered_count", models.IntegerField(default=0)),
                ("time_taken_seconds", models.IntegerField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="tests_engine.test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_answer",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("is_correct", models.BooleanField(null=True)),
                ("time_taken_seconds", models.IntegerField(blank=True, null=True)),
                ("is_marked_for_review", models.BooleanField(default=False)),
                (
                    "confidence_level",
                    models.IntegerField(
                        blank=True, help_text="1-5 confidence rating", null=True
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="tests_engine.testattempt",
                    ),
                ),
            ],
            options={
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
