# Generated by Django 5.2.12 on 2026-04-17 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_engine", "0002_test_version_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
