# Generated by Django 5.2.12 on 2026-07-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_engine", "0003_alter_test_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("cms", "UPSC CMS"),
                    ("neet_pg", "NEET PG"),
                    ("usmle", "USMLE"),
                    ("fmge", "FMGE"),
                ],
                default="cms",
                max_length=20,
            ),
        ),
    ]
