# Generated by Django 5.2.12 on 2026-08-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_engine", "0005_one_active_test_attempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="is_free_preview",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Free users may start this test even without a subscription. Admin curates 2.",
            ),
        ),
    ]
