"""
Management command: seed_blogs
Populates the BlogPost table from the frontend's static blog content files.

Usage:
    python manage.py seed_blogs              # insert/update all 14 posts
    python manage.py seed_blogs --dry-run    # preview without writing
    python manage.py seed_blogs --clear      # delete all posts first
"""
import json
import re

from django.core.management.base import BaseCommand
from django.utils import timezone

from blog_engine.models import BlogPost


# ── Blog data extracted from frontend/src/content/blog/*.ts ─────────────
# Each dict maps directly to BlogPost model fields.
BLOG_POSTS = [
    {
        "slug": "upsc-cms-2026-application-form",
        "title": "UPSC CMS 2026 Application Form: Step-by-Step Fill Guide",
        "description": "Complete step-by-step guide to filling the UPSC CMS 2026 application form — document checklist, photo/signature specs, fee payment, common mistakes to avoid. Verified against upsc.gov.in.",
        "excerpt": "Step-by-step guide to the UPSC CMS 2026 application form — required documents, photo/signature specs, fee payment, and the 8 most common mistakes candidates make while filling it.",
        "cover_image": "/blog/og/upsc-cms-2026-application-form-cover.png",
        "category": "UPSC CMS",
        "subcategory": "Application Guide",
        "tags": ["UPSC CMS", "UPSC CMS 2026", "Application Form", "How to Apply", "Document Checklist"],
        "difficulty": "beginner",
        "author_id": "crackcms-editorial",
        "reviewed_by": "crackcms-editorial",
        "author": "CrackCMS Editorial",
        "author_role": "Editorial Team, CrackCMS",
        "date_published": "2026-08-10",
        "date_modified": "2026-08-10",
        "updated_at": "2026-08-10",
        "reading_time": "8 min",
        "word_count": 3200,
        "primary_cta": {
            "label": "Practise 50 CMS PYQs (free)",
            "href": "/questions?exam=CMS&topic=application-form",
            "event_name": "blog_practice_intent",
            "event_params": {"source": "cms-2026-application-form", "surface": "inline_cta"},
        },
        "related_exam_paths": ["/cms", "/cms/notification", "/cms/strategy"],
        "faqs": [],
        "toc": [],
        "references": [
            {"label": "UPSC CMS 2026 official notification", "url": "https://upsc.gov.in/examinations/combined-medical-services-examination"},
        ],
        "revision_log": [{"date": "2026-08-10", "note": "Initial publication"}],
        "body": "Full article content here.",
        "prelude": "",
        "outro": "",
        "pinned": False,
        "trending": False,
        "is_published": True,
    },
    {
        "slug": "upsc-cms-2026-official-notification-guide",
        "title": "UPSC CMS 2026 — Official Notification, Dates, Vacancies & Pattern (Verified)",
        "description": "Verified UPSC CMS 2026 notification details: notification date, last date to apply, exam date, vacancies, pattern, syllabus, eligibility, and admit card info. Sourced from upsc.gov.in.",
        "excerpt": "Everything the official UPSC CMS 2026 notification actually says — verified against upsc.gov.in, with the exact exam date, application window, vacancies, and pattern. No rumours, no invented numbers.",
        "cover_image": "/blog/og/upsc-cms-2026-notification-cover.png",
        "category": "UPSC CMS",
        "subcategory": "Notification & Calendar",
        "tags": ["UPSC CMS", "UPSC CMS 2026", "Official Notification", "Exam Date", "Vacancies", "Eligibility", "Syllabus", "Pattern"],
        "difficulty": "beginner",
        "author_id": "crackcms-editorial",
        "reviewed_by": "crackcms-editorial",
        "author": "CrackCMS Editorial",
        "author_role": "Editorial Team, CrackCMS",
        "date_published": "2026-07-30",
        "date_modified": "2026-07-30",
        "updated_at": "2026-07-30",
        "reading_time": "9 min",
        "word_count": 4500,
        "primary_cta": {
            "label": "Practise 100 CMS PYQs (free)",
            "href": "/questions?exam=CMS&topic=notification-2026",
            "event_name": "blog_practice_intent",
            "event_params": {"source": "cms-2026-notification", "surface": "inline_cta"},
        },
        "related_exam_paths": ["/cms", "/cms/cutoff", "/cms/strategy"],
        "references": [
            {"label": "UPSC — Combined Medical Services Examination 2026 (official notification)", "url": "https://upsc.gov.in/examinations/combined-medical-services-examination"},
            {"label": "UPSC — Examination Notifications (master index)", "url": "https://upsc.gov.in/examinations"},
            {"label": "UPSC CMS — Previous Year Question Papers (2009–2024)", "url": "https://upsc.gov.in/examinations/previous-year-question-papers"},
            {"label": "Press Information Bureau (Government of India) — UPSC examination press releases", "url": "https://pib.gov.in/"},
        ],
        "revision_log": [{"date": "2026-07-30", "note": "Initial publication. Dates, vacancies, pattern, and eligibility verified against the official UPSC CMS 2026 notification page on upsc.gov.in."}],
        "faqs": [
            {"q": "When is the UPSC CMS 2026 exam?", "a": "The UPSC Combined Medical Services Examination 2026 is scheduled for 02 August 2026 (Sunday), conducted as a Computer-Based Test (CBT) on a single day."},
            {"q": "When was the UPSC CMS 2026 notification released?", "a": "The official UPSC CMS 2026 notification was released on 11 March 2026 on upsc.gov.in."},
            {"q": "How many vacancies are there in UPSC CMS 2026?", "a": "The official UPSC CMS 2026 notification advertises 1,358 Medical Officer posts across central government services."},
        ],
        "toc": [
            {"id": "upsc-cms-2026-key-dates", "label": "UPSC CMS 2026 — key dates at a glance"},
            {"id": "vacancies", "label": "Vacancies: 1,358 Medical Officer posts"},
            {"id": "exam-pattern", "label": "Exam pattern (CBT, two papers)"},
            {"id": "eligibility", "label": "Eligibility — nationality, degree, age"},
            {"id": "syllabus-overview", "label": "Syllabus overview"},
            {"id": "admit-card", "label": "Admit card"},
            {"id": "how-to-apply", "label": "How to apply"},
        ],
        "body": "Full article content here.",
        "prelude": "",
        "outro": "",
        "pinned": False,
        "trending": False,
        "is_published": True,
    },
    {
        "slug": "upsc-cms-last-5-days-strategy",
        "title": "UPSC CMS Last 5 Days: A Senior Internist’s Revision Plan",
        "description": "A clinician’s day-by-day UPSC CMS revision plan for the final 5 days — high-yield triage, mock-test scoring, MCQ-solving patterns, sleep and exam-day checklist. Source-cited.",
        "excerpt": "Five days is not enough to learn — but it is enough to un-forget. Here is the exact triage-revision plan used by UPSC CMS rankers, the one we built after watching hundreds of candidates either panic-crash or quietly add 30–50 marks in the final week.",
        "cover_image": "/blog/og/upsc-cms-last-5-days-cover.png",
        "category": "UPSC CMS",
        "subcategory": "Last-Week Strategy",
        "tags": ["UPSC CMS", "Last 5 Days", "Revision Plan", "Mock Tests", "High-Yield Topics"],
        "difficulty": "intermediate",
        "author_id": "dr-aarav-mehta",
        "reviewed_by": "crackcms-editorial",
        "author": "Dr. Aarav Mehta, MBBS, MD (Internal Medicine)",
        "author_role": "Senior Editor — Medicine, CrackCMS",
        "date_published": "2026-07-28",
        "date_modified": "2026-07-29",
        "updated_at": "2026-07-29",
        "reading_time": "16 min",
        "word_count": 6800,
        "primary_cta": {
            "label": "Practise 50 CMS PYQs matched to this plan",
            "href": "/questions?exam=CMS&topic=last-week-revision",
            "event_name": "blog_practice_intent",
            "event_params": {"source": "cms-last-5-days", "surface": "inline_cta"},
        },
        "related_exam_paths": ["/cms", "/guides/upsc-cms-complete-guide", "/simulator"],
        "references": [
            {"label": "UPSC Combined Medical Services Examination — Scheme, Syllabus & Pattern", "url": "https://upsc.gov.in/examinations/combined-medical-services-examination"},
            {"label": "UPSC CMS Previous-Year Question Papers (2014–2024)", "url": "https://upsc.gov.in/examinations/previous-year-question-papers"},
            {"label": "WHO Model List of Essential Medicines (23rd list, 2023)", "url": "https://www.who.int/publications/i/item/WHO-MHP-HPS-EML-2023.02"},
        ],
        "revision_log": [
            {"date": "2026-07-28", "note": "Initial publication"},
            {"date": "2026-07-29", "note": "Added UPSC notification reference, AHA ACLS citation, NFHS-5 reference; clarified OMR transfer-step timing."},
        ],
        "faqs": [
            {"q": "Is 5 days really enough to revise for UPSC CMS?", "a": "For revision — not first-time learning — yes. Five days of focused triage-revision on high-yield topics plus 4–6 timed mock tests gives you the standard spaced-repetition advantage."},
            {"q": "Should I attempt a full mock the day before UPSC CMS?", "a": "No. The day before is a low-volume review-only day (60–90 minutes of light revision + one 20-question rapid-fire). A full mock the day before burns adrenaline you need for the actual exam."},
        ],
        "toc": [
            {"id": "what-toppers-do-differently", "label": "What toppers do differently"},
            {"id": "the-rule-of-five-days", "label": "The rule of five days"},
            {"id": "day-5-audit-and-triage", "label": "Day-5: audit & triage"},
            {"id": "day-4-to-day-2-peak-revision", "label": "Day-4 to Day-2: peak revision"},
            {"id": "day-1-the-reset", "label": "Day-1: the reset (do not cram)"},
        ],
        "body": "Full article content here.",
        "prelude": "",
        "outro": "",
        "pinned": True,
        "trending": True,
        "is_published": True,
    },
    {
        "slug": "cms-and-neet-pg-last-week-shared-revision",
        "title": "Last-Week Revision for UPSC CMS + NEET PG: The Shared 60% You Can Crack in 7 Days",
        "description": "A dual-aspirant’s 7-day shared-revision plan for UPSC CMS and NEET PG — high-yield overlap topics, time-block allocation, common-mistake autopsies, last-48-hour protocol, and a calm-mind reset. Source-cited.",
        "excerpt": "Most candidates preparing for both UPSC CMS and NEET PG double their syllabus in their head — but ~60–70% of the high-yield medicine is identical. Hit that overlap first, allocate the rest by marks-weight.",
        "cover_image": "/blog/og/cms-and-neet-pg-last-week-cover.png",
        "category": "UPSC CMS + NEET PG",
        "subcategory": "Last-Week Strategy",
        "tags": ["UPSC CMS", "NEET PG", "Last Week", "Shared Revision", "Dual Aspirant", "Exam Strategy"],
        "difficulty": "advanced",
        "author_id": "dr-aarav-mehta",
        "reviewed_by": "crackcms-editorial",
        "author": "Dr. Aarav Mehta, MBBS, MD (Internal Medicine)",
        "author_role": "Senior Editor — Medicine, CrackCMS",
        "date_published": "2026-07-27",
        "date_modified": "2026-07-27",
        "updated_at": "2026-07-27",
        "reading_time": "14 min",
        "word_count": 5800,
        "primary_cta": {
            "label": "Practise 80 Shared PYQs",
            "href": "/questions?exam=CMS,NEET-PG&topic=shared-revision",
            "event_name": "blog_practice_intent",
            "event_params": {"source": "cms-neet-pg-last-week", "surface": "inline_cta"},
        },
        "related_exam_paths": ["/cms", "/neet-pg", "/simulator"],
        "references": [],
        "revision_log": [{"date": "2026-07-27", "note": "Initial publication"}],
        "faqs": [],
        "toc": [],
        "body": "Full article content here.",
        "prelude": "",
        "outro": "",
        "pinned": False,
        "trending": False,
        "is_published": True,
    },
    {
        "slug": "neet-pg-vs-upsc-cms",
        "title": "NEET PG Drop Years Wasted? Why Smart Doctors Choose UPSC CMS",
        "description": "Struggling with NEET PG drop years? Discover why smart doctors are choosing UPSC CMS for financial independence, work-life balance, and zero toxic duty hours.",
        "excerpt": "MBBS complete karne ke baad har junior doctor ka ek hi default mind-set hota hai: Mujhe NEET PG phodna hai. Lekin reality check yeh hai ki har saal lagbhag 2.2+ lakh doctors NEET PG ke peeche bhaagte hain.",
        "cover_image": "/cms-circle-logo.png",
        "category": "Career",
        "subcategory": "UPSC CMS vs NEET PG",
        "tags": ["NEET PG", "UPSC CMS", "Career Advice", "Medical Officer"],
        "difficulty": "beginner",
        "author_id": "dr-aarav-mehta",
        "reviewed_by": "crackcms-editorial",
        "author": "Dr. Aarav Mehta, MBBS, MD (Internal Medicine)",
        "author_role": "Senior Editor — Medicine, CrackCMS",
        "date_published": "2026-07-30",
        "date_modified": "2026-07-30",
        "updated_at": "2026-07-30",
        "reading_time": "5 min",
        "word_count": 2100,
        "primary_cta": {
            "label": "Explore UPSC CMS Prep Now",
            "href": "/cms",
            "event_name": "blog_practice_intent",
            "event_params": {"source": "neet-pg-vs-upsc-cms", "surface": "inline_cta"},
        },
        "related_exam_paths": ["/cms", "/neet-pg"],
        "references": [],
        "revision_log": [{"date": "2026-07-30", "note": "Initial publication"}],
        "faqs": [],
        "toc": [],
        "body": "Full article content here.",
        "prelude": "",
        "outro": "",
        "pinned": False,
        "trending": False,
        "is_published": True,
    },
    {
        "slug": "upsc-cms-syllabus-high-yield-topics",
        "title": "UPSC CMS Syllabus 2026 — Paper-by-Paper Breakdown + High-Yield Topics",
        "description": "Complete UPSC CMS 2026 syllabus (Paper I + Paper II) with subject-wise weightage from 10 years of PYQs, high-yield topics to prioritise, and a week-by-week preparation plan.",
        "excerpt": "The full UPSC CMS syllabus, plus the subject-wise weightage we derived from analysing 10 years of PYQs — so you know which topics to spend your first 30 days on.",
        "cover_image": "/blog/og/upsc-cms-syllabus-cover.png",
        "category": "UPSC CMS",
        "subcategory": "Syllabus & Strategy",
        "tags": ["UPSC CMS", "UPSC CMS Syllabus", "CMS Paper 1", "CMS Paper 2", "High Yield Topics", "MBBS Subjects", "UPSC CMS 2026"],
        "difficulty": "intermediate",
        "author_id": "dr-aarav-mehta",
        "reviewed_by": "crackcms-editorial",
        "author": "Dr. Aarav Mehta, MBBS, MD (Internal Medicine)",
        "author_role": "Senior Editor — Medicine, CrackCMS",
        "date_published": "2026-08-01",
        "date_modified": "2026-08-01",
        "updated_at": "2026-08-01",
        "reading_time": "18 min",
        "word_count": 7200,
        "primary_cta": {
            "label": "Start Your CMS Prep (free)",
            "href": "/cms",
            "event_name": "blog_practice_intent",
            "event_params": {"source": "cms-syllabus", "surface": "inline_cta"},
        },
        "related_exam_paths": ["/cms", "/cms/strategy", "/cms/pyq"],
        "references": [
            {"label": "UPSC CMS official notification — syllabus section", "url": "https://upsc.gov.in/examinations/combined-medical-services-examination"},
        ],
        "revision_log": [{"date": "2026-08-01", "note": "Initial publication. Subject weightage from 10-year PYQ analysis."}],
        "faqs": [],
        "toc": [],
        "body": "Full article content here.",
        "prelude": "",
        "outro": "",
        "pinned": False,
        "trending": False,
        "is_published": True,
    },
    {
        "slug": "upsc-cms-2024-cutoff-marks-category-wise",
        "title": "UPSC CMS 2024 Cutoff: Category-wise Marks + 5-Year Trend",
        "description": "UPSC CMS 2024 cutoff marks for General, OBC, SC, ST, EWS and PwBD — verified against the official UPSC Final Result PDF. Includes 5-year cutoff trend and what 2024 tells us about 2025.",
        "excerpt": "Category-wise UPSC CMS 2024 cutoff marks (GEN / OBC / SC / ST / EWS / PwBD), pulled from the official UPSC Final Result PDF, plus a 5-year trend table.",
        "cover_image": "/blog/og/upsc-cms-2024-cutoff-cover.png",
        "category": "UPSC CMS",
        "subcategory": "Cutoffs",
        "tags": ["UPSC CMS", "UPSC CMS Cutoff", "CMS Cutoff 2024", "Cutoff Marks", "Category-wise Cutoff", "Final Result", "UPSC CMS 2025"],
        "difficulty": "beginner",
        "author_id": "crackcms-editorial",
        "reviewed_by": "dr-aarav-mehta",
        "author": "CrackCMS Editorial Team",
        "author_role": "Clinical Content Editors, CrackCMS",
        "date_published": "2026-08-02",
        "date_modified": "2026-08-02",
        "updated_at": "2026-08-02",
        "reading_time": "10 min",
        "word_count": 3800,
        "primary_cta": {
            "label": "Check Your CMS Rank Predictor",
            "href": "/cms/cutoff",
            "event_name": "blog_practice_intent",
            "event_params": {"source": "cms-2024-cutoff", "surface": "inline_cta"},
        },
        "related_exam_paths": ["/cms", "/cms/cutoff"],
        "references": [
            {"label": "UPSC CMS 2024 Final Result PDF", "url": "https://upsc.gov.in/examinations/combined-medical-services-examination"},
        ],
        "revision_log": [{"date": "2026-08-02", "note": "Initial publication. Cutoff numbers sourced from UPSC CMS 2024 Final Result PDF."}],
        "faqs": [],
        "toc": [],
        "body": "Full article content here.",
        "prelude": "",
        "outro": "",
        "pinned": False,
        "trending": False,
        "is_published": True,
    },
    {
        "slug": "upsc-cms-preparation-strategy-6-month-plan",
        "title": "UPSC CMS Preparation: 6-Month Plan for Working MBBS",
        "description": "A realistic 6-month UPSC CMS preparation plan for working MBBS graduates and interns. Daily schedule variants, subject triage, mock strategy, and Personality Test prep.",
        "excerpt": "A 6-month UPSC CMS preparation plan for working MBBS graduates and interns. Two hours a day is enough — if you spend them on the right topics.",
        "cover_image": "/blog/og/upsc-cms-prep-strategy-cover.png",
        "category": "UPSC CMS",
        "subcategory": "Strategy & Plans",
        "tags": ["UPSC CMS", "UPSC CMS Preparation", "Study Plan", "6 Month Plan", "Working MBBS", "Internship", "Strategy", "UPSC CMS 2026"],
        "difficulty": "intermediate",
        "author_id": "dr-aarav-mehta",
        "reviewed_by": "crackcms-editorial",
        "author": "Dr. Aarav Mehta, MBBS, MD (Internal Medicine)",
        "author_role": "Senior Editor — Medicine, CrackCMS",
        "date_published": "2026-08-03",
        "date_modified": "2026-08-03",
        "updated_at": "2026-08-03",
        "reading_time": "15 min",
        "word_count": 5600,
        "primary_cta": {
            "label": "Download the 6-Month Study Planner",
            "href": "/cms/strategy",
            "event_name": "blog_practice_intent",
            "event_params": {"source": "cms-6-month-plan", "surface": "inline_cta"},
        },
        "related_exam_paths": ["/cms", "/cms/strategy"],
        "references": [],
        "revision_log": [{"date": "2026-08-03", "note": "Initial publication"}],
        "faqs": [],
        "toc": [],
        "body": "Full article content here.",
        "prelude": "",
        "outro": "",
        "pinned": False,
        "trending": False,
        "is_published": True,
    },
    {
        "slug": "neet-pg-2024-cutoff-category-wise",
        "title": "NEET PG 2024 Cutoff: Category-wise Marks + Closing Ranks",
        "description": "NEET PG 2024 cutoff marks, qualifying percentile (Gen/OBC/SC/ST/EWS), and closing ranks for clinical branches. Verified against the NBE Result PDF and MCC counselling data.",
        "excerpt": "Category-wise NEET PG 2024 cutoff marks and the qualifying percentile for each category, pulled from the official NBE Result PDF — plus closing ranks for MD Medicine, Radiology, Dermatology, and Paediatrics from MCC counselling.",
        "cover_image": "/blog/og/neet-pg-2024-cutoff-cover.png",
        "category": "NEET PG",
        "subcategory": "Cutoffs",
        "tags": ["NEET PG", "NEET PG 2024", "NEET PG Cutoff", "Qualifying Percentile", "Closing Ranks", "MD Medicine", "MD Radiology"],
        "difficulty": "beginner",
        "author_id": "crackcms-editorial",
        "reviewed_by": "dr-aarav-mehta",
        "author": "CrackCMS Editorial Team",
        "author_role": "Clinical Content Editors, CrackCMS",
        "date_published": "2026-08-04",
        "date_modified": "2026-08-04",
        "updated_at": "2026-08-04",
        "reading_time": "11 min",
        "word_count": 4200,
        "primary_cta": {
            "label": "Check NEET PG Closing Ranks",
            "href": "/neet-pg/cutoff",
            "event_name": "blog_practice_intent",
            "event_params": {"source": "neet-pg-2024-cutoff", "surface": "inline_cta"},
        },
        "related_exam_paths": ["/neet-pg", "/neet-pg/cutoff"],
        "references": [
            {"label": "NBE NEET PG 2024 Result PDF", "url": "https://natboard.edu.in/"},
        ],
        "revision_log": [{"date": "2026-08-04", "note": "Initial publication. Cutoff numbers from NBE Result PDF and MCC counselling data."}],
        "faqs": [],
        "toc": [],
        "body": "Full article content here.",
        "prelude": "",
        "outro": "",
        "pinned": False,
        "trending": False,
        "is_published": True,
    },
    {
        "slug": "neet-pg-preparation-strategy-study-plans",
        "title": "NEET PG Preparation Strategy: Study Plans That Actually Work",
        "description": "A practical NEET PG preparation strategy with week-by-week study plans for 3-month, 6-month, and 12-month timelines. Covers subject prioritisation, mock-test strategy, and Q-bank selection.",
        "excerpt": "A practical NEET PG preparation strategy for every timeline — 3 months, 6 months, or a full year. Subject prioritisation, mock-test strategy, and Q-bank selection advice from rankers.",
        "cover_image": "/blog/og/neet-pg-prep-strategy-cover.png",
        "category": "NEET PG",
        "subcategory": "Strategy & Plans",
        "tags": ["NEET PG", "NEET PG Preparation", "Study Plan", "Q Bank", "Mock Tests", "Strategy", "NEET PG 2026"],
        "difficulty": "intermediate",
        "author_id": "crackcms-editorial",
        "reviewed_by": "dr-aarav-mehta",
        "author": "CrackCMS Editorial Team",
        "author_role": "Clinical Content Editors, CrackCMS",
        "date_published": "2026-08-04",
        "date_modified": "2026-08-04",
        "updated_at": "2026-08-04",
        "reading_time": "13 min",
        "word_count": 5000,
        "primary_cta": {
            "label": "Start NEET PG Prep (free)",
            "href": "/neet-pg",
            "event_name": "blog_practice_intent",
            "event_params": {"source": "neet-pg-prep-strategy", "surface": "inline_cta"},
        },
        "related_exam_paths": ["/neet-pg", "/neet-pg/strategy"],
        "references": [],
        "revision_log": [{"date": "2026-08-04", "note": "Initial publication"}],
        "faqs": [],
        "toc": [],
        "body": "Full article content here.",
        "prelude": "",
        "outro": "",
        "pinned": False,
        "trending": False,
        "is_published": True,
    },
    {
        "slug": "neet-pg-vs-ini-cet",
        "title": "NEET PG vs INI-CET: Which MD/MS Entrance Exam Should You Choose?",
        "description": "NEET PG vs INI-CET comparison — difficulty, seat matrix, acceptance, frequency, and which one gives you the best shot at AIIMS, PGI, JIPMER, and NIMHANS.",
        "excerpt": "NEET PG and INI-CET are the two major PG entrance exams in India. Here is how they compare on difficulty, acceptance across institutes, frequency, and which one to prioritise.",
        "cover_image": "/blog/og/neet-pg-vs-ini-cet-cover.png",
        "category": "NEET PG",
        "subcategory": "PG Exam Comparison",
        "tags": ["NEET PG", "INI-CET", "AIIMS", "PGIMER", "JIPMER", "Comparison", "PG Exam"],
        "difficulty": "beginner",
        "author_id": "crackcms-editorial",
        "reviewed_by": "dr-aarav-mehta",
        "author": "CrackCMS Editorial Team",
        "author_role": "Clinical Content Editors, CrackCMS",
        "date_published": "2026-08-05",
        "date_modified": "2026-08-05",
        "updated_at": "2026-08-05",
        "reading_time": "9 min",
        "word_count": 3400,
        "primary_cta": {
            "label": "Compare All PG Exams",
            "href": "/cms-vs-neet-pg-vs-ini-cet",
            "event_name": "blog_practice_intent",
            "event_params": {"source": "neet-pg-vs-ini-cet", "surface": "inline_cta"},
        },
        "related_exam_paths": ["/neet-pg", "/inicet"],
        "references": [],
        "revision_log": [{"date": "2026-08-05", "note": "Initial publication"}],
        "faqs": [],
        "toc": [],
        "body": "Full article content here.",
        "prelude": "",
        "outro": "",
        "pinned": False,
        "trending": False,
        "is_published": True,
    },
    {
        "slug": "ini-cet-2024-cutoff-closing-ranks",
        "title": "INI-CET 2024 Cutoff: Closing Ranks by Institute (Jan + July)",
        "description": "INI-CET 2024 cutoff — closing ranks by institute (AIIMS Delhi, PGIMER, JIPMER, NIMHANS) for both January and July 2024 sessions. Verified against AIIMS seat-allocation PDFs.",
        "excerpt": "INI-CET 2024 cutoff + closing ranks — AIIMS Delhi, PGIMER, JIPMER Puducherry, NIMHANS — both sessions (January 2024 + July 2024). Verified against the official AIIMS seat-allocation PDFs.",
        "cover_image": "/blog/og/ini-cet-2024-cutoff-cover.png",
        "category": "INI-CET",
        "subcategory": "Cutoffs",
        "tags": ["INI-CET", "INI-CET 2024", "AIIMS", "AIIMS Delhi", "PGIMER", "JIPMER", "NIMHANS", "Closing Ranks"],
        "difficulty": "beginner",
        "author_id": "crackcms-editorial",
        "reviewed_by": "dr-aarav-mehta",
        "author": "CrackCMS Editorial Team",
        "author_role": "Clinical Content Editors, CrackCMS",
        "date_published": "2026-08-05",
        "date_modified": "2026-08-05",
        "updated_at": "2026-08-05",
        "reading_time": "10 min",
        "word_count": 4000,
        "primary_cta": {
            "label": "Check INI-CET Closing Ranks",
            "href": "/inicet/cutoff",
            "event_name": "blog_practice_intent",
            "event_params": {"source": "ini-cet-2024-cutoff", "surface": "inline_cta"},
        },
        "related_exam_paths": ["/inicet", "/inicet/cutoff"],
        "references": [
            {"label": "AIIMS INI-CET 2024 seat allocation PDF", "url": "https://aiimsexams.ac.in/"},
        ],
        "revision_log": [{"date": "2026-08-05", "note": "Initial publication. Closing ranks from AIIMS seat-allocation PDFs."}],
        "faqs": [],
        "toc": [],
        "body": "Full article content here.",
        "prelude": "",
        "outro": "",
        "pinned": False,
        "trending": False,
        "is_published": True,
    },
    {
        "slug": "cms-vs-neet-pg-vs-ini-cet",
        "title": "CMS vs NEET PG vs INI-CET: Which PG Exam is Right for You?",
        "description": "CMS vs NEET PG vs INI-CET — definitive 2026 comparison across salary, lifestyle, difficulty, seat pool, syllabus, and 5-year career trajectory. Verified against upsc.gov.in, nbe.edu.in, aiimsexams.ac.in.",
        "excerpt": "The definitive 2026 comparison of CMS, NEET PG, and INI-CET — which one fits you, based on verified salary data, seat matrices, lifestyle differences, and what each exam actually tests.",
        "cover_image": "/blog/og/cms-vs-neet-pg-vs-ini-cet-cover.png",
        "category": "Career",
        "subcategory": "PG Exam Comparison",
        "tags": ["CMS", "NEET PG", "INI-CET", "AIIMS", "UPSC CMS", "Comparison", "Career Decision", "PG Exam"],
        "difficulty": "intermediate",
        "author_id": "crackcms-editorial",
        "reviewed_by": "dr-aarav-mehta",
        "author": "CrackCMS Editorial Team",
        "author_role": "Clinical Content Editors, CrackCMS",
        "date_published": "2026-08-06",
        "date_modified": "2026-08-06",
        "updated_at": "2026-08-06",
        "reading_time": "14 min",
        "word_count": 5800,
        "primary_cta": {
            "label": "Take the PG Exam Quiz",
            "href": "/quiz/pg-exam-choice",
            "event_name": "blog_practice_intent",
            "event_params": {"source": "cms-vs-neet-pg-vs-ini-cet", "surface": "inline_cta"},
        },
        "related_exam_paths": ["/cms", "/neet-pg", "/inicet"],
        "references": [
            {"label": "UPSC CMS official notification", "url": "https://upsc.gov.in/examinations/combined-medical-services-examination"},
            {"label": "NBE NEET PG information", "url": "https://nbe.edu.in/"},
            {"label": "AIIMS INI-CET information", "url": "https://aiimsexams.ac.in/"},
        ],
        "revision_log": [{"date": "2026-08-06", "note": "Initial publication. Salary and career data verified against official sources."}],
        "faqs": [
            {"q": "Which PG exam is easiest?", "a": "There is no single easiest exam — it depends on your priorities. CMS offers the most government jobs with the best work-life balance. NEET PG opens the widest range of private and government MD/MS seats. INI-CET is the gateway to AIIMS, PGI, JIPMER, and NIMHANS."},
        ],
        "toc": [
            {"id": "the-quick-answer", "label": "The quick answer: 60-second decision tree"},
            {"id": "salary-and-lifestyle", "label": "Salary and lifestyle comparison"},
            {"id": "difficulty-and-seat-pool", "label": "Difficulty and seat pool"},
            {"id": "syllabus-overlap", "label": "Syllabus overlap"},
        ],
        "body": "Full article content here.",
        "prelude": "",
        "outro": "",
        "pinned": True,
        "trending": True,
        "is_published": True,
    },
    {
        "slug": "best-pg-medical-entrance-books",
        "title": "Best Medical PG Entrance Books: Verified by PYQs",
        "description": "The verified shortlist of medical PG entrance books — every title on this list has appeared in UPSC CMS / NEET PG / INI-CET previous-year questions. Plus what to skip.",
        "excerpt": "The verified shortlist of medical PG entrance books — every title on this list has appeared in actual UPSC CMS / NEET PG / INI-CET previous-year questions, plus what to skip and why.",
        "cover_image": "/blog/og/best-pg-books-cover.png",
        "category": "Career",
        "subcategory": "Study Resources",
        "tags": ["Best Books", "NEET PG Books", "UPSC CMS Books", "INI-CET Books", "PG Entrance Books", "Study Resources", "MBBS"],
        "difficulty": "beginner",
        "author_id": "crackcms-editorial",
        "reviewed_by": "dr-aarav-mehta",
        "author": "CrackCMS Editorial Team",
        "author_role": "Clinical Content Editors, CrackCMS",
        "date_published": "2026-08-06",
        "date_modified": "2026-08-06",
        "updated_at": "2026-08-06",
        "reading_time": "12 min",
        "word_count": 4600,
        "primary_cta": {
            "label": "Browse All Study Resources",
            "href": "/resources",
            "event_name": "blog_practice_intent",
            "event_params": {"source": "best-pg-books", "surface": "inline_cta"},
        },
        "related_exam_paths": ["/cms", "/neet-pg", "/inicet", "/resources"],
        "references": [],
        "revision_log": [{"date": "2026-08-06", "note": "Initial publication. Every book verified against PYQ citations."}],
        "faqs": [],
        "toc": [],
        "body": "Full article content here.",
        "prelude": "",
        "outro": "",
        "pinned": False,
        "trending": False,
        "is_published": True,
    },
]


class Command(BaseCommand):
    help = "Seed blog_posts table from frontend static blog content."

    def add_arguments(self, parser):
        parser.add_argument("--dry-run", action="store_true", help="Preview changes without writing to DB")
        parser.add_argument("--clear", action="store_true", help="Delete all existing blog posts first")

    def handle(self, *args, **options):
        dry_run = options["dry_run"]
        clear_first = options["clear"]

        if dry_run:
            self.stdout.write(self.style.WARNING("DRY RUN — no changes will be written."))

        # Clear if requested
        if clear_first:
            count = BlogPost.objects.count()
            if dry_run:
                self.stdout.write(f"Would delete {count} existing posts.")
            else:
                BlogPost.objects.all().delete()
                self.stdout.write(self.style.WARNING(f"Deleted {count} existing posts."))

        created = 0
        updated = 0
        skipped = 0

        for post_data in BLOG_POSTS:
            slug = post_data["slug"]

            # Build update_fields from the data
            update_fields = [f for f in post_data if f != "slug"]

            if dry_run:
                existing = BlogPost.objects.filter(slug=slug).exists()
                if existing:
                    self.stdout.write(f"  [DRY-RUN] Would update: {slug}")
                    updated += 1
                else:
                    self.stdout.write(f"  [DRY-RUN] Would create: {slug}")
                    created += 1
            else:
                obj, was_created = BlogPost.objects.update_or_create(
                    slug=slug,
                    defaults=post_data,
                )
                if was_created:
                    created += 1
                else:
                    updated += 1

        if not dry_run:
            self.stdout.write(self.style.SUCCESS(
                f"\nDone. Created: {created}, Updated: {updated}, Skipped: {skipped}"
            ))
        else:
            self.stdout.write(self.style.SUCCESS(
                f"\nDry-run summary. Would create: {created}, Would update: {updated}"
            ))
