import type { ComparisonContent } from '@/components/ComparisonLayout';

/**
 * Side-by-side comparisons between medical exams. Each entry ships as a
 * complete ComparisonContent ready to render via ComparisonLayout.
 */

export const CMS_VS_NEETPG: ComparisonContent = {
    examASlug: 'cms',
    examBSlug: 'neet-pg',
    examAName: 'UPSC CMS',
    examBName: 'NEET PG',
    examALandingPath: '/cms',
    examBLandingPath: '/neet-pg',
    description: 'UPSC CMS vs NEET PG — side-by-side comparison of exam pattern (240 vs 200 questions), negative marking (−0.33 vs −1), total marks (1060 vs 800), salary, difficulty, success rate, and which one to pick based on your career goals.',
    verdict: 'UPSC CMS and NEET PG are both postgraduate medical exams but for different career tracks. CMS leads to central government medical officer roles; NEET PG leads to MD/MS specialisation.',
    chooseA: [
        'You want a central government medical officer position (Railways, CHS, ESIC)',
        'You prefer a non-clinical / administrative career path',
        'You want to settle early with a stable gazetted post',
        'You do not want to do a 3-year residency',
    ],
    chooseB: [
        'You want a clinical MD/MS in a specific branch (Medicine, Surgery, Radio, Anaesthesia)',
        'You want to become a superspecialist later (DM/MCh)',
        'You are willing to invest 3 years of residency for a clinical career',
        'You want private practice + hospital consultant track',
    ],
    rows: [
        { label: 'Conducting body', examA: 'UPSC', examB: 'NBE' },
        { label: 'Frequency', examA: 'Once a year', examB: 'Once a year' },
        { label: 'Pattern', examA: '2 papers × 120 Qs = 240 Qs', examB: '200 Qs (single paper, CBT)' },
        { label: 'Negative marking', examA: 'Yes (−0.33)', examB: 'Yes (−1 per wrong answer, since 2019)' },
        { label: 'Total marks (written)', examA: '960 (4 marks × 240 Qs)', examB: '800 (4 marks × 200 Qs)' },
        { label: 'Final score', examA: '960 written + 100 interview = 1060', examB: '800 (only written, no interview)' },
        { label: 'Time', examA: '2 hours per paper', examB: '3.5 hours' },
        { label: 'Subjects', examA: 'Medicine, Surgery, Paediatrics, OBG, PSM + minor', examB: 'All 19 pre-clinical, para-clinical and clinical subjects' },
        { label: 'Difficulty', examA: 'Moderate (clinic-heavy, less depth)', examB: 'Hard (depth + breadth across 19 subjects)' },
        { label: 'Success rate', examA: '~1-3% of applicants qualify', examB: '~50% qualify for counselling, ~10% get top branch' },
        { label: 'Outcome', examA: 'MO / CHS / GDMO post (₹80k-₹1.2L in-hand)', examB: 'MD/MS seat (₹70k-₹1.5L stipend during residency, then 5-30L private)' },
        { label: 'Career ceiling', examA: 'Add. Director General, DGHS, CMOs', examB: 'Prof, HOD, superspecialist, hospital consultant' },
        { label: 'Preparation time', examA: '6 months typical', examB: '12-18 months typical' },
    ],
    faqs: [
        { q: 'Which is harder, UPSC CMS or NEET PG?', a: 'NEET PG is broader (19 subjects, 800 marks, 200 Qs in one go) and considered harder for most candidates. UPSC CMS is clinic-focused (240 Qs across 2 papers) and easier to cover in 6 months.' },
        { q: 'Can I prepare for UPSC CMS and NEET PG together?', a: 'Yes — the two exams overlap ~70% in syllabus. Most candidates use NEET PG prep as a base and add UPSC-CMS-specific PSM and Surgery depth.' },
        { q: 'Which pays more, UPSC CMS or NEET PG?', a: 'NEET PG leads to clinical specialisation with much higher long-term earnings (₹20L-₹1Cr+ private practice). UPSC CMS gives a stable ₹80k-₹1.2L government salary from day one.' },
        { q: 'Should I attempt UPSC CMS if I already qualified NEET PG?', a: 'If you want a clinical career, take the MD/MS seat. If you want a stable government post without 3 years of residency, attempt UPSC CMS the same year — both exams are around 6 months apart.' },
    ],
    relatedLinks: [
        { label: 'UPSC CMS Preparation Guide 2026', href: '/cms' },
        { label: 'NEET PG Preparation Guide 2026', href: '/neet-pg' },
        { label: 'UPSC CMS vs NEET PG: Which Should You Choose? (Blog)', href: '/blog/upsc-cms-vs-neet-pg-comparison' },
        { label: 'UPSC CMS Cutoff 2025', href: '/blog/upsc-cms-cutoff-2025' },
        { label: 'NEET PG Cutoff 2024', href: '/blog/neet-pg-cutoff-2024' },
        { label: 'Last Week Shared Revision: CMS + NEET PG', href: '/blog/last-week-shared-revision-cms-neet-pg' },
        { label: 'Best PG Medical Entrance Books 2026', href: '/blog/best-pg-medical-entrance-books-2026' },
        { label: 'High-Yield Topics for Every Paper', href: '/blog/high-yield-topics' },
    ],
};

export const CMS_VS_INICET: ComparisonContent = {
    examASlug: 'cms',
    examBSlug: 'ini-cet',
    examAName: 'UPSC CMS',
    examBName: 'INI-CET',
    examALandingPath: '/cms',
    examBLandingPath: '/ini-cet',
    description: 'UPSC CMS vs INI-CET — compare exam pattern, negative marking (−0.33 vs −1), salary during training vs posting, AIIMS/PGI/JIPMER MD seats vs central government medical officer posts, difficulty level, and career growth.',
    verdict: 'UPSC CMS leads to central government medical officer posts; INI-CET leads to MD/MS seats at AIIMS, PGIMER, JIPMER, NIMHANS. Different career tracks with different lifestyles.',
    chooseA: [
        'You want a gazetted medical officer post without residency',
        'You prefer a non-clinical or administrative career',
        'You want work-life balance from day one',
        'You have not done a year of internship yet',
    ],
    chooseB: [
        'You want to specialise at AIIMS / PGI / JIPMER',
        'You want a clinical academic career',
        'You are willing to do 3 years of residency at a top central institute',
        'You want superspecialisation (DM/MCh) afterwards',
    ],
    rows: [
        { label: 'Conducting body', examA: 'UPSC', examB: 'AIIMS New Delhi' },
        { label: 'Frequency', examA: 'Once a year', examB: 'Twice a year (Jan + July)' },
        { label: 'Pattern', examA: '240 Qs, 2 papers, 120 min each', examB: '200 Qs, single paper, 180 min' },
        { label: 'Negative marking', examA: 'Yes (−0.33)', examB: 'Yes (−1)' },
        { label: 'Outcome', examA: 'MO / CHS / GDMO post', examB: 'MD/MS/MDS at AIIMS/PGI/JIPMER/NIMHANS' },
        { label: 'Salary during', examA: '₹80k-₹1.2L from day one', examB: '₹90k-₹1.1L stipend during residency' },
        { label: 'Post-residency', examA: 'Same as above', examB: 'Senior Resident ₹1.2-1.8L, then faculty track' },
        { label: 'Career ceiling', examA: 'Add. DG, DGHS, CMO', examB: 'Prof, HOD, Dean, Director AIIMS' },
        { label: 'Syllabus depth', examA: 'Clinic-heavy, 5 main subjects', examB: 'All 19 subjects, deeper' },
        { label: 'Cutoff difficulty', examA: 'Moderate', examB: 'High (limited AIIMS seats)' },
    ],
    faqs: [
        { q: 'Which is harder, UPSC CMS or INI-CET?', a: 'INI-CET is harder because of more negative marking (−1 vs −0.33), deeper syllabus, and limited seats at top central institutes.' },
        { q: 'Is INI-CET tougher than NEET PG?', a: 'INI-CET is generally considered slightly tougher due to deeper clinical reasoning and tighter negative marking, but the syllabus is the same as NEET PG.' },
        { q: 'Can I attempt UPSC CMS and INI-CET in the same year?', a: 'Yes — both happen around July-November, allowing back-to-back attempts. Many candidates use CMS as a backup if INI-CET does not yield a seat.' },
    ],
    relatedLinks: [
        { label: 'UPSC CMS Preparation Guide 2026', href: '/cms' },
        { label: 'INI-CET Preparation Guide 2026', href: '/ini-cet' },
        { label: 'INI-CET Cutoff 2024', href: '/blog/ini-cet-cutoff-2024' },
        { label: 'INI-CET Study Plan (4-Month)', href: '/blog/ini-cet-study-plan' },
        { label: 'UPSC CMS vs NEET PG Comparison', href: '/cms/vs-neet-pg' },
        { label: 'High-Yield Topics for Every Paper', href: '/blog/high-yield-topics' },
    ],
};

export const NEETPG_VS_USMLE: ComparisonContent = {
    examASlug: 'neet-pg',
    examBSlug: 'usmle',
    examAName: 'NEET PG',
    examBName: 'USMLE',
    examALandingPath: '/neet-pg',
    examBLandingPath: '/usmle',
    description: 'NEET PG vs USMLE — exam pattern, prep time, cost, career path, and which one to pick as an Indian MBBS graduate. Step 1, Step 2 CK, and residency matching compared.',
    verdict: 'NEET PG is for Indian PG seats (₹2-15L total cost, 12-18 month prep). USMLE leads to US residency (₹15-25L total cost, 18-30 month prep) but requires navigating the Match process with ~50% success for IMGs.',
    chooseA: [
        'You want to specialise and practise in India',
        'You have financial constraints (USMLE prep + residency applications are expensive)',
        'You want a faster path to PG',
        'You want to be close to family',
    ],
    chooseB: [
        'You want to practise in the US',
        'You can afford ₹15-25L in prep + application costs',
        'You have strong USMLE scores (Step 1 pass + Step 2 CK ≥250)',
        'You want global research + clinical exposure',
    ],
    rows: [
        { label: 'Country', examA: 'India', examB: 'United States' },
        { label: 'Conducting body', examA: 'NBE', examB: 'NBME / FSMB / ECFMG' },
        { label: 'Pattern', examA: '200 Qs, single paper, 210 min', examB: 'Step 1: pass/fail (approx. 8h); Step 2 CK: ~320 Qs (9h)' },
        { label: 'Negative marking', examA: 'Yes (−1 per wrong)', examB: 'No (Step 1 pass/fail; Step 2 CK no negative marking)' },
        { label: 'Prep time', examA: '12-18 months', examB: '18-30 months' },
        { label: 'Total cost', examA: '₹2-15L (incl. coaching)', examB: '₹15-25L (incl. travel, ECFMG, applications)' },
        { label: 'Outcome', examA: 'MD/MS seat in India', examB: 'US residency match (ACGME program)' },
        { label: 'Residency duration', examA: '3 years', examB: '3-7 years (depends on specialty)' },
        { label: 'Salary after residency', examA: '₹10L-₹1Cr+ private', examB: '₹$180k-500k (₹1.5-4.2Cr) US average' },
        { label: 'Practice location', examA: 'India', examB: 'USA, then optional return' },
    ],
    faqs: [
        { q: 'Is USMLE harder than NEET PG?', a: 'Step 1 became pass/fail in January 2022 — there is no numeric score. USMLE tests applied clinical reasoning, while NEET PG tests depth across 19 subjects. Matching into a US residency as an IMG is the real challenge (~50% match rate).' },
        { q: 'Should Indian MBBS students attempt USMLE?', a: 'If you can afford ₹15-25L, have strong academics, and want global exposure, USMLE is worth it. NEET PG remains the practical choice for most Indian graduates seeking MD/MS seats.' },
        { q: 'Can I prepare for USMLE and NEET PG together?', a: 'Yes — pre-clinical and clinical subjects overlap heavily. Many Indian aspirants use First Aid + UWorld for USMLE while solving NEET PG MCQs alongside.' },
    ],
    relatedLinks: [
        { label: 'NEET PG Preparation Guide 2026', href: '/neet-pg' },
        { label: 'USMLE Step 1 Guide', href: '/usmle' },
        { label: 'NEET PG vs USMLE: Full Comparison (Blog)', href: '/blog/neet-pg-vs-usmle-comparison' },
        { label: 'NEET PG 6-Month Strategy', href: '/blog/neet-pg-6-month-strategy' },
        { label: 'NEET PG Mock Test Strategy', href: '/blog/neet-pg-mock-strategy' },
        { label: 'High-Yield Topics for Every Paper', href: '/blog/high-yield-topics' },
        { label: 'Best PG Medical Entrance Books 2026', href: '/blog/best-pg-medical-entrance-books-2026' },
    ],
};

export const FMGE_VS_NEXT: ComparisonContent = {
    examASlug: 'fmge',
    examBSlug: 'neet-pg',
    examAName: 'FMGE',
    examBName: 'NEXT',
    examALandingPath: '/fmge',
    examBLandingPath: '/neet-pg',
    description: 'FMGE vs NEXT — what changes for Indian students who completed MBBS abroad. Comparison of pattern, eligibility, negative marking, and career impact.',
    verdict: 'FMGE is the current licensing exam for foreign MBBS graduates (single paper, 300 Qs, no negative marking). NEXT (National Exit Test) will eventually replace FMGE as a combined licensing + PG entrance exam, but the rollout has been delayed. As of 2026, FMGE remains the mandatory screening exam.',
    chooseA: [
        'You are graduating or have already graduated from a foreign MBBS programme',
        'You need the Screening Test to register with the NMC',
        'You want a single exam focused on licensing (not combined with PG ranking)',
    ],
    chooseB: [
        'You want ONE exam that serves both as a license and PG entrance',
        'You want a competency-based assessment (not pure MCQ-based)',
        'You are in an early year of MBBS abroad and can plan for the transition',
    ],
    rows: [
        { label: 'Conducting body', examA: 'NBE (on behalf of NMC)', examB: 'NMC / NBE (planned)' },
        { label: 'Pattern', examA: '300 Qs, single paper, 150 min, CBT', examB: 'Single computer-based exam with multiple sections' },
        { label: 'Negative marking', examA: 'No negative marking', examB: 'No negative marking (proposed)' },
        { label: 'Frequency', examA: 'Twice a year (June + December)', examB: 'Expected twice a year (not confirmed)' },
        { label: 'Pass mark', examA: '150/300 (50%)', examB: 'Competency-based threshold (not defined yet)' },
        { label: 'Outcome', examA: 'License to practise in India + internship', examB: 'License to practise + PG entrance rank' },
        { label: 'Eligibility', examA: 'Foreign MBBS graduates with ECFMG equivalency', examB: 'All MBBS graduates (Indian + foreign)' },
        { label: 'Internship', examA: '12-month Indian internship required before practice', examB: 'Likely integrated into exam structure' },
    ],
    faqs: [
        { q: 'Is FMGE being replaced by NEXT?', a: 'Yes, NEXT is planned to replace FMGE for foreign graduates and will also serve as the PG entrance exam replacing NEET PG. However, the rollout has faced repeated delays. As of 2026, FMGE remains the active exam.' },
        { q: 'Should I still prepare for FMGE if NEXT is coming?', a: 'Absolutely — until NEXT is officially implemented, FMGE is the only way for foreign graduates to get licensed in India. Your FMGE preparation overlaps heavily with NEXT preparation (clinical subjects, preventive medicine).' },
        { q: 'What is the FMGE pass rate?', a: 'FMGE pass rate hovers around 15-25%, making it a challenging exam. NEXT, when implemented, is expected to have a more structured competency-based approach.' },
    ],
    relatedLinks: [
        { label: 'FMGE Exam Guide', href: '/fmge' },
        { label: 'FMGE vs NEXT: Full Comparison (Blog)', href: '/blog/fmge-vs-next-comparison' },
        { label: 'FMGE Preparation Strategy', href: '/blog/fmge-exam-guide' },
        { label: 'Best PG Medical Entrance Books 2026', href: '/blog/best-pg-medical-entrance-books-2026' },
        { label: 'Time Management for Medical Exams', href: '/blog/time-management' },
    ],
};

export const NEETPG_VS_UPSC_CMS: ComparisonContent = {
    examASlug: 'neet-pg',
    examBSlug: 'cms',
    examAName: 'NEET PG',
    examBName: 'UPSC CMS',
    examALandingPath: '/neet-pg',
    examBLandingPath: '/cms',
    description: 'NEET PG vs UPSC CMS: Which exam should you choose after MBBS? Compare syllabus overlap, difficulty, salary, career growth, exam pattern, and which one matches your goals.',
    verdict: 'NEET PG leads to MD/MS clinical specialisation with higher long-term earnings. UPSC CMS leads to a central government Medical Officer post with stable salary and job security from day one. Both exams overlap ~70% in syllabus — most candidates attempt both.',
    chooseA: [
        'You want a clinical MD/MS in a specific branch (Medicine, Surgery, Radiology, Anaesthesia)',
        'You want to become a superspecialist later (DM/MCh)',
        'You are willing to invest 3 years of residency for long-term growth',
        'You want private practice or hospital consultant track',
    ],
    chooseB: [
        'You want a stable central government medical officer post (Railways, CHS, ESIC)',
        'You prefer a non-clinical or administrative career path',
        'You want work-life balance from day one without 3 years of residency',
        'You value job security, pension, and government perks',
    ],
    rows: [
        { label: 'Conducting body', examA: 'NBE', examB: 'UPSC' },
        { label: 'Frequency', examA: 'Once a year', examB: 'Once a year' },
        { label: 'Pattern', examA: '200 MCQs, single paper, 3.5 hours, 800 marks', examB: '240 MCQs, 2 papers, 2 hrs each, 960 marks' },
        { label: 'Negative marking', examA: 'No', examB: 'Yes (-0.33 per wrong answer)' },
        { label: 'Mode', examA: 'CBT', examB: 'Offline (pen-and-paper OMR)' },
        { label: 'Subjects', examA: 'All 19 pre-clinical, para-clinical, clinical subjects', examB: 'Medicine, Surgery, Paediatrics, OBG, PSM + minor subjects' },
        { label: 'Difficulty', examA: 'Hard (breadth across 19 subjects)', examB: 'Moderate (clinic-heavy, less depth)' },
        { label: 'Outcome', examA: 'MD/MS seat (residency)', examB: 'Medical Officer / GDMO post' },
        { label: 'Starting income', examA: '₹70k-₹1L stipend during 3-year residency', examB: '₹80k-₹1.2L from day one' },
        { label: 'Long-term earnings', examA: '₹20L-₹1Cr+ (private practice)', examB: '₹1.5L-₹2L (govt scale)' },
        { label: 'Career ceiling', examA: 'Prof, HOD, superspecialist, hospital consultant', examB: 'CMO, ADG, DGHS' },
        { label: 'Prep time', examA: '12-18 months typical', examB: '6 months typical' },
    ],
    faqs: [
        { q: 'Which is better, NEET PG or UPSC CMS?', a: 'It depends on your career goals. NEET PG is better if you want clinical MD/MS specialisation and long-term earning potential. UPSC CMS is better if you want a stable government job with work-life balance from day one without spending 3 years in residency.' },
        { q: 'Can I prepare for NEET PG and UPSC CMS together?', a: 'Yes — the two exams overlap ~70% in syllabus. Most candidates use NEET PG prep as a base and add UPSC-CMS-specific PSM and Surgery depth. Both exams are around 6 months apart, allowing back-to-back attempts.' },
        { q: 'Which pays more, NEET PG or UPSC CMS?', a: 'NEET PG leads to clinical specialisation with much higher long-term earnings (₹20L-₹1Cr+ in private practice). UPSC CMS gives a stable ₹80k-₹1.2L government salary from day one with excellent job security and pension benefits.' },
        { q: 'Is UPSC CMS tougher than NEET PG?', a: 'NEET PG is generally considered harder because of its breadth (19 subjects, 200 Qs in one sitting). UPSC CMS is clinic-focused (240 Qs across 2 papers) and can be covered in 6 months with focused preparation.' },
    ],
};

export const NEETPG_VS_INICET: ComparisonContent = {
    examASlug: 'neet-pg',
    examBSlug: 'ini-cet',
    examAName: 'NEET PG',
    examBName: 'INI-CET',
    examALandingPath: '/neet-pg',
    examBLandingPath: '/ini-cet',
    description: 'NEET PG vs INI-CET — which PG entrance exam is right for you? Compare pattern, difficulty, negative marking, seats, stipend, institutes (AIIMS/PGI/JIPMER vs all India), and preparation strategy.',
    verdict: 'NEET PG opens MD/MS seats across all medical colleges in India (~10,000+ seats). INI-CET opens PG seats only at AIIMS, PGIMER, JIPMER, NIMHANS, SCTIMST (~1,000-1,500 seats) but with higher brand value. Syllabus is ~80% overlapping. Most serious candidates attempt both.',
    chooseA: [
        'You want MD/MS seats across all medical colleges (including private and state)',
        'You prefer a broader, more predictable exam pattern',
        'You want counselling through MCC (centralised all-India counselling)',
        'You are targeting a specific branch and want maximum seat options',
    ],
    chooseB: [
        'You want a PG seat at AIIMS, PGI, JIPMER, NIMHANS, SCTIMST',
        'You thrive on conceptual, image-based questions',
        'You want the prestige and research opportunities of central institutes',
        'You want two chances per year (January + July sessions)',
    ],
    rows: [
        { label: 'Conducting body', examA: 'NBE', examB: 'AIIMS New Delhi' },
        { label: 'Frequency', examA: 'Once a year (June)', examB: 'Twice a year (Jan + July)' },
        { label: 'Questions', examA: '200 MCQs, 3.5 hours', examB: '200 MCQs, 3 hours' },
        { label: 'Negative marking', examA: 'No', examB: 'Yes (-1/3 per wrong answer)' },
        { label: 'Total marks', examA: '800', examB: '200' },
        { label: 'Mode', examA: 'CBT', examB: 'CBT' },
        { label: 'Institutes', examA: 'All medical colleges in India', examB: 'AIIMS, PGI, JIPMER, NIMHANS, SCTIMST only' },
        { label: 'Seats', examA: '~10,000+ MD/MS seats', examB: '~1,000-1,500 PG seats' },
        { label: 'Difficulty', examA: 'Hard (breadth across 19 subjects)', examB: 'Harder (depth + image-based + -1/3)' },
        { label: 'Stipend', examA: '₹70k-₹1L/month', examB: '₹90k-₹1.1L/month' },
    ],
    faqs: [
        { q: 'Which is tougher, NEET PG or INI-CET?', a: 'INI-CET is generally considered slightly tougher due to deeper clinical reasoning, image-based questions, and -1/3 negative marking. NEET PG is broader but has more memory-based questions and no negative marking.' },
        { q: 'Is INI-CET and NEET PG syllabus same?', a: 'Yes — both cover the same 19 pre-clinical, para-clinical and clinical subjects. INI-CET questions tend to be more conceptual and image-based, while NEET PG has more direct recall questions.' },
        { q: 'Can I appear for both NEET PG and INI-CET?', a: 'Yes — NEET PG is once yearly (June), INI-CET is twice yearly (Jan + July). Many serious candidates attempt both to maximise PG seat options. The syllabus is ~80% overlapping.' },
        { q: 'Which institutes are under INI-CET?', a: 'INI-CET is the common entrance for AIIMS (all campuses), PGIMER Chandigarh, JIPMER Puducherry, NIMHANS Bangalore, and SCTIMST Trivandrum.' },
    ],
};

export const ALL_COMPARISONS: Record<string, ComparisonContent> = {
    'cms/vs-neet-pg': CMS_VS_NEETPG,
    'cms/vs-ini-cet': CMS_VS_INICET,
    'neet-pg/vs-usmle': NEETPG_VS_USMLE,
    'neet-pg/vs-ini-cet': NEETPG_VS_INICET,
    'neet-pg/vs-upsc-cms': NEETPG_VS_UPSC_CMS,
    'fmge/vs-next': FMGE_VS_NEXT,
};