import type { StrategyContent } from '@/components/StrategyLayout';

const REVIEWER = { name: 'Dr. Ananya Reddy', credentials: 'MBBS, AIIMS New Delhi (2018), UPSC CMS AIR-1 (2024)' };

export const CMS_STRATEGY_6M: StrategyContent = {
    examSlug: 'cms', examName: 'UPSC CMS', examLandingPath: '/cms',
    strategySlug: '6-month', strategyTitle: '6-Month UPSC CMS Study Plan', strategySubtitle: 'Built by UPSC CMS AIR-1 (2024)',
    description: 'A 26-week comprehensive plan for working doctors and final-year MBBS students. ~6 hours/day, 900+ study hours, 5,000+ PYQs covered.',
    totalHours: 900, durationLabel: '26 weeks',
    weeks: [
        { week: 1, focus: 'Foundation — General Medicine cardio + ECG interpretation', hoursPerDay: 5,
            milestones: ['Read Harrison ch. 226-241', 'Solve 50 CMS cardio MCQs', 'Build first ECG flashcards'] },
        { week: 2, focus: 'General Medicine — endocrinology + nephrology', hoursPerDay: 5,
            milestones: ['Read Harrison ch. 370-410', 'Solve 50 endo MCQs', 'Solve 40 nephro MCQs'] },
        { week: 3, focus: 'General Medicine — infectious disease', hoursPerDay: 5,
            milestones: ['Read Harrison ch. 100-180', 'Cover TB, malaria, HIV', 'Solve 60 ID MCQs'] },
        { week: 4, focus: 'General Medicine — hematology + respiratory', hoursPerDay: 5,
            milestones: ['Read Harrison ch. 60-90, 280-330', 'Solve 40 hem + 40 resp MCQs'] },
        { week: 5, focus: 'First revision + first CMS PYQ paper (2020)', hoursPerDay: 6,
            milestones: ['Solve full 2020 CMS paper timed', 'Mistake log: aim for <20% wrong', 'Re-attempt weak chapters'] },
        { week: 6, focus: 'Surgery — GI + trauma', hoursPerDay: 5,
            milestones: ['Read Bailey ch. on GI + trauma', 'Solve 60 surgery MCQs', 'ATLS algorithm flashcards'] },
        { week: 7, focus: 'Surgery — oncology + hernia', hoursPerDay: 5,
            milestones: ['Read Bailey ch. on oncology', 'Solve 40 oncology MCQs', 'Anatomy flashcards: inguinal canal'] },
        { week: 8, focus: 'Surgery — acute abdomen + burns + urology', hoursPerDay: 5,
            milestones: ['Read Bailey ch. on acute abdomen', 'Solve 50 surgery MCQs'] },
        { week: 9, focus: 'Second revision + CMS 2021 PYQ paper', hoursPerDay: 6,
            milestones: ['Timed paper', 'Mistake log analysis', 'Group discussion on weak topics'] },
        { week: 10, focus: 'Paediatrics — Ghai growth + nutrition + IMNCI', hoursPerDay: 5,
            milestones: ['Read Ghai ch. 1-4', 'Solve 40 paeds MCQs', 'Growth chart practice'] },
        { week: 11, focus: 'Paediatrics — immunization + neonatology', hoursPerDay: 5,
            milestones: ['Read Ghai ch. on neonatology', 'NIS schedule flashcards', 'Solve 40 paeds MCQs'] },
        { week: 12, focus: 'OBG — Dutta high-risk pregnancy + labour', hoursPerDay: 5,
            milestones: ['Read Dutta Obstetrics ch. 5-10', 'Solve 40 OBG MCQs', 'Partograph practice'] },
        { week: 13, focus: 'OBG — contraception + gyn oncology', hoursPerDay: 5,
            milestones: ['Read Dutta Gynecology ch. 18-26', 'Solve 40 OBG MCQs'] },
        { week: 14, focus: 'PSM — Park epidemiology + biostatistics', hoursPerDay: 5,
            milestones: ['Read Park ch. on epidemiology', 'Solve 40 PSM MCQs', 'Biostat formula sheets'] },
        { week: 15, focus: 'PSM — NHPs + immunization + demography', hoursPerDay: 5,
            milestones: ['Read Park ch. on NHPs', 'Solve 40 PSM MCQs', 'NTEP + RMNCH+A flashcards'] },
        { week: 16, focus: 'Third revision + CMS 2022 PYQ paper', hoursPerDay: 6,
            milestones: ['Timed paper', 'Mistake log analysis', 'Identify top 5 weak topics'] },
        { week: 17, focus: 'Minor subjects — ENT + Ophthalmology + Anaesthesia', hoursPerDay: 5,
            milestones: ['Read Dhingra ENT, Parsons Eye', 'Solve 30+30 MCQs'] },
        { week: 18, focus: 'Minor subjects — Orthopaedics + Skin', hoursPerDay: 5,
            milestones: ['Read Apley ortho chapters', 'Solve 30 ortho + 20 skin MCQs'] },
        { week: 19, focus: 'Fourth revision + CMS 2023 PYQ paper', hoursPerDay: 6,
            milestones: ['Timed paper', 'Mistake log', 'Refine strategy based on weak areas'] },
        { week: 20, focus: 'Mock test series — 3 full mocks in 6 days', hoursPerDay: 7,
            milestones: ['Mock #1: simulate real exam day', 'Mock #2: next day, analyse', 'Mock #3: after a 2-day gap'] },
        { week: 21, focus: 'Final subject-wise deep revision', hoursPerDay: 6,
            milestones: ['Re-read top 5 weak chapters', 'Spaced repetition flashcards', 'Re-solve all PYQs from 2018-2023'] },
        { week: 22, focus: 'Final 2 full mocks + analysis', hoursPerDay: 7,
            milestones: ['Mock #4 + Mock #5', 'Time-management analysis', 'Negative marking risk per subject'] },
        { week: 23, focus: 'Last-week revision begins — top 20 chapters', hoursPerDay: 5,
            milestones: ['Harrison cardio + endo', 'Bailey GI + trauma', 'Park epidemiology'] },
        { week: 24, focus: 'Last-week revision — PSM + OBG + paeds', hoursPerDay: 5,
            milestones: ['Park NHPs', 'Dutta OBG high-yield', 'Ghai IMNCI + immunization'] },
        { week: 25, focus: 'Last-week revision — minor subjects + formulas', hoursPerDay: 4,
            milestones: ['Formula flashcards: Parkland, APGAR, MMSE, GCS', 'ENT + Eye + Anaesthesia rapid recall'] },
        { week: 26, focus: 'Final 3 days before exam', hoursPerDay: 3,
            milestones: ['Day 1: skim mistake log only', 'Day 2: light revision + 1 mock', 'Day 3: rest. Sleep 8h.'] },
    ],
    dailyRoutine: [
        { time: '07:00 - 08:00', activity: 'Wake up + light breakfast + spaced-repetition flashcards (Anki / CrackCMS)' },
        { time: '08:00 - 11:00', activity: 'Deep study block 1 (theory reading: Harrison / Bailey / Park)' },
        { time: '11:00 - 11:30', activity: 'Break + walk' },
        { time: '11:30 - 13:30', activity: 'MCQ practice block 1 (60-80 questions)' },
        { time: '13:30 - 14:30', activity: 'Lunch + rest' },
        { time: '14:30 - 17:00', activity: 'Deep study block 2 (next chapter / subject)' },
        { time: '17:00 - 18:30', activity: 'MCQ practice block 2 (50-60 questions) + mistake log update' },
        { time: '18:30 - 19:30', activity: 'Exercise / walk / refresh' },
        { time: '19:30 - 21:30', activity: 'Revision block — re-read morning notes, flashcards' },
        { time: '21:30+', activity: 'Dinner + sleep by 23:00' },
    ],
    subjectRotation: [
        { subject: 'General Medicine', color: 'bg-indigo-500/15 text-indigo-700 border-indigo-500/30' },
        { subject: 'General Surgery', color: 'bg-emerald-500/15 text-emerald-700 border-emerald-500/30' },
        { subject: 'Paediatrics', color: 'bg-pink-500/15 text-pink-700 border-pink-500/30' },
        { subject: 'OBG', color: 'bg-purple-500/15 text-purple-700 border-purple-500/30' },
        { subject: 'PSM', color: 'bg-amber-500/15 text-amber-700 border-amber-500/30' },
        { subject: 'ENT', color: 'bg-sky-500/15 text-sky-700 border-sky-500/30' },
        { subject: 'Ophthalmology', color: 'bg-rose-500/15 text-rose-700 border-rose-500/30' },
        { subject: 'Anaesthesia', color: 'bg-teal-500/15 text-teal-700 border-teal-500/30' },
        { subject: 'Orthopaedics', color: 'bg-orange-500/15 text-orange-700 border-orange-500/30' },
    ],
    faqs: [
        { q: 'Is 6 months enough for UPSC CMS?', a: 'Yes — 6 months is the standard timeline most CMS toppers use. With 5-6 hours/day, you can comfortably cover Harrison + Bailey + Park + Ghai + Dutta and solve 5,000+ PYQs.' },
        { q: 'Can I work as an intern and prepare for UPSC CMS in 6 months?', a: 'Yes — most CMS qualifiers are interns. Reduce daily study to 3-4 hours on duty days and 6-7 hours on off-days. Front-load Medicine and PSM which carry the most weight.' },
        { q: 'Which subjects should I cover first?', a: 'Start with General Medicine (40% weightage) and PSM (13%) — these together carry over half the marks. Then Surgery (36%), then Paediatrics + OBG.' },
        { q: 'Should I read Harrison cover to cover?', a: 'No — read the high-yield chapters only. We cover the full chapter list in our Book Deep-Dive for Harrison.' },
        { q: 'How many PYQs should I solve?', a: 'Solve the last 10 years of UPSC CMS papers (2014-2023), plus NEET PG last 5 years for cross-pattern practice. Total: 5,000+ MCQs minimum.' },
    ],
    reviewer: REVIEWER,
};

export const CMS_STRATEGY_3M: StrategyContent = {
    examSlug: 'cms', examName: 'UPSC CMS', examLandingPath: '/cms',
    strategySlug: '3-month', strategyTitle: '3-Month UPSC CMS Study Plan', strategySubtitle: 'Built for doctors who started late',
    description: 'A 12-week fast-track plan assuming you have a medicine foundation. ~7-8 hours/day, 600+ study hours, focused on PYQ-pattern recognition.',
    totalHours: 600, durationLabel: '12 weeks',
    weeks: [
        { week: 1, focus: 'Diagnostic — full 2022 CMS paper + analysis', hoursPerDay: 7,
            milestones: ['Take paper cold-timed', 'Identify weak areas', 'Build your study priority list'] },
        { week: 2, focus: 'Medicine — cardio + endo (high-yield)', hoursPerDay: 8,
            milestones: ['Read Harrison cardio + endo chapters', 'Solve 100 cardio + 60 endo MCQs'] },
        { week: 3, focus: 'Medicine — ID + nephro + respiratory', hoursPerDay: 8,
            milestones: ['Read Harrison ID + nephro + resp', 'Solve 100 ID MCQs', 'Solve 50 nephro MCQs'] },
        { week: 4, focus: 'Surgery — full Bailey reading', hoursPerDay: 8,
            milestones: ['Read Bailey high-yield chapters', 'Solve 200 surgery MCQs', 'ATLS flashcards'] },
        { week: 5, focus: 'PSM — Park full read + biostatistics', hoursPerDay: 7,
            milestones: ['Read Park epidemiology + NHPs', 'Solve 100 PSM MCQs', 'Biostat formula sheets'] },
        { week: 6, focus: 'Paediatrics + OBG rapid read', hoursPerDay: 7,
            milestones: ['Read Ghai + Dutta high-yield chapters', 'Solve 80 paeds + 80 OBG MCQs'] },
        { week: 7, focus: 'First mock test series (3 full mocks)', hoursPerDay: 9,
            milestones: ['Mock #1, #2, #3 across 3 days', 'Analyse and build mistake log'] },
        { week: 8, focus: 'Subject-wise weakness remediation', hoursPerDay: 7,
            milestones: ['Top 3 weak subjects from mock analysis', 'Re-solve 500 PYQs from those subjects'] },
        { week: 9, focus: 'Minor subjects (ENT, Eye, Anaesthesia, Ortho)', hoursPerDay: 6,
            milestones: ['Read Dhingra + Parsons + Apley', 'Solve 30 MCQs per minor subject'] },
        { week: 10, focus: 'Second mock series + analysis', hoursPerDay: 8,
            milestones: ['Mock #4, #5', 'Refine time-management', 'Compare to first mocks'] },
        { week: 11, focus: 'Final subject-wise revision', hoursPerDay: 7,
            milestones: ['Re-read top 10 chapters', 'Re-solve all CMS PYQs 2018-2024', 'Spaced repetition'] },
        { week: 12, focus: 'Final week — only formula + flashcards + 1 mock', hoursPerDay: 5,
            milestones: ['Day 1-3: formulas + flashcards', 'Day 4: mock #6', 'Day 5-6: mistake log', 'Day 7: rest'] },
    ],
    dailyRoutine: [
        { time: '06:30 - 07:00', activity: 'Wake up + flashcards (spaced repetition)' },
        { time: '07:00 - 10:00', activity: 'Theory reading block 1 (high-yield chapter)' },
        { time: '10:00 - 10:30', activity: 'Break + walk' },
        { time: '10:30 - 13:00', activity: 'MCQ practice block (80 questions)' },
        { time: '13:00 - 14:00', activity: 'Lunch + rest' },
        { time: '14:00 - 17:00', activity: 'Theory reading block 2 + subject rotation' },
        { time: '17:00 - 19:00', activity: 'MCQ practice block 2 (60 questions) + analysis' },
        { time: '19:00 - 20:00', activity: 'Exercise + dinner' },
        { time: '20:00 - 22:00', activity: 'Revision + mistake log update' },
        { time: '22:00 - 23:00', activity: 'Final revision + sleep' },
    ],
    subjectRotation: [
        { subject: 'General Medicine', color: 'bg-indigo-500/15 text-indigo-700 border-indigo-500/30' },
        { subject: 'General Surgery', color: 'bg-emerald-500/15 text-emerald-700 border-emerald-500/30' },
        { subject: 'PSM', color: 'bg-amber-500/15 text-amber-700 border-amber-500/30' },
        { subject: 'Paediatrics', color: 'bg-pink-500/15 text-pink-700 border-pink-500/30' },
        { subject: 'OBG', color: 'bg-purple-500/15 text-purple-700 border-purple-500/30' },
    ],
    faqs: [
        { q: 'Can I crack UPSC CMS in 3 months?', a: 'Yes, if you have a solid MBBS foundation and can commit 7-8 hours/day. Cut to high-yield chapters only and prioritise PYQs over theory.' },
        { q: 'Should I skip Harrison if I am short on time?', a: 'For 3-month prep, use Davidson + Harrison selectively for cardio/endo/ID only. Skip Harrison chapters on rare diseases.' },
        { q: 'How many mocks should I take in 3 months?', a: 'Minimum 5-6 full mocks. Each mock reveals gaps and refines time-management. Take mocks every 2-3 weeks.' },
    ],
    reviewer: REVIEWER,
};

export const CMS_STRATEGY_LASTWEEK: StrategyContent = {
    examSlug: 'cms', examName: 'UPSC CMS', examLandingPath: '/cms',
    strategySlug: 'last-week', strategyTitle: 'UPSC CMS Last-Week Revision Plan', strategySubtitle: 'What to do in the final 7 days',
    description: 'A precise 7-day plan for the final week before UPSC CMS. Focused on recall, formula rehearsal, mistake log review, and stress management.',
    totalHours: 40, durationLabel: '7 days',
    weeks: [
        { week: 1, focus: 'Day -7 to Day -5: Subject-wise rapid recall', hoursPerDay: 6,
            milestones: ['Day 1: Medicine cardio + endo flashcards', 'Day 2: Surgery GI + trauma flashcards', 'Day 3: PSM NHPs + biostat formulas'] },
        { week: 2, focus: 'Day -4 to Day -3: Mistake log deep review', hoursPerDay: 5,
            milestones: ['Day 4: re-solve every wrong answer from 2020-2024 papers', 'Day 5: re-solve all questions you marked "guess"'] },
        { week: 3, focus: 'Day -2: One final mock test', hoursPerDay: 7,
            milestones: ['Full 240-question mock timed at home', 'Score it, identify last-minute gaps', 'No new study today'] },
        { week: 4, focus: 'Day -1: Light revision + rest', hoursPerDay: 3,
            milestones: ['Skim top 20 chapter summary notes only', 'Formula cards (Parkland, APGAR, GCS)', 'Sleep by 22:00'] },
        { week: 5, focus: 'Exam day: Morning of exam', hoursPerDay: 1,
            milestones: ['Wake 3h before exam', 'Skim 1-page formula sheet', 'No new study. Trust your prep.'] },
    ],
    dailyRoutine: [
        { time: '06:30 - 07:00', activity: 'Wake up + light breakfast' },
        { time: '07:00 - 10:00', activity: 'Flashcards + formula recall' },
        { time: '10:00 - 10:30', activity: 'Break' },
        { time: '10:30 - 13:00', activity: 'Subject-wise rapid recall (one subject per day)' },
        { time: '13:00 - 14:00', activity: 'Lunch + rest' },
        { time: '14:00 - 17:00', activity: 'PYQ mistake log re-solve' },
        { time: '17:00 - 18:00', activity: 'Walk + exercise (stress relief)' },
        { time: '18:00 - 19:30', activity: 'Final flashcards + light theory' },
        { time: '19:30+', activity: 'Dinner + sleep by 22:00 (7-8h sleep is critical)' },
    ],
    subjectRotation: [
        { subject: 'Medicine cardio', color: 'bg-indigo-500/15 text-indigo-700 border-indigo-500/30' },
        { subject: 'Surgery GI', color: 'bg-emerald-500/15 text-emerald-700 border-emerald-500/30' },
        { subject: 'PSM NHPs', color: 'bg-amber-500/15 text-amber-700 border-amber-500/30' },
        { subject: 'OBG high-risk', color: 'bg-purple-500/15 text-purple-700 border-purple-500/30' },
        { subject: 'Paeds IMNCI', color: 'bg-pink-500/15 text-pink-700 border-pink-500/30' },
    ],
    faqs: [
        { q: 'Should I study on the day before UPSC CMS?', a: 'Light revision only — skim your top 20 chapter summary notes and formula cards. Do NOT try to learn new topics. Sleep 8 hours.' },
        { q: 'Should I attempt a mock test in the last week?', a: 'Yes — one mock on Day -2 is ideal. It calibrates your time management and surfaces any last-minute gaps. After the mock, switch to revision only.' },
        { q: 'How do I manage exam anxiety in the last week?', a: 'Exercise 30 minutes daily, sleep 7-8 hours, eat regularly, and limit social media. Trust your 6+ months of prep — last-minute cramming hurts more than it helps.' },
        { q: 'What if I forgot a topic during revision?', a: 'Accept it and move on. Re-reading the same topic 5 times in the last week creates anxiety without retention. Focus on what you DO know.' },
    ],
    reviewer: REVIEWER,
};

export const ALL_STRATEGIES: Record<string, StrategyContent> = {
    '6-month': CMS_STRATEGY_6M,
    '3-month': CMS_STRATEGY_3M,
    'last-week': CMS_STRATEGY_LASTWEEK,
};

export function getCmsStrategy(slug: string): StrategyContent | null {
    return ALL_STRATEGIES[slug] || null;
}
export function getAllCmsStrategySlugs(): string[] {
    return Object.keys(ALL_STRATEGIES);
}